//! Bulk operations
//!
//! Generated by metaphor-schema. Do not edit manually.

pub mod shared_types;
pub use shared_types::*;

pub mod timeoff_balance_bulk;
pub mod timeoff_request_bulk;
pub mod timeoff_type_bulk;

pub use timeoff_balance_bulk::TimeoffBalanceBulkService;
pub use timeoff_request_bulk::TimeoffRequestBulkService;
pub use timeoff_type_bulk::TimeoffTypeBulkService;

// <<< CUSTOM
// END CUSTOM
