//! Bulk operations for TimeoffRequest entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericBulkService` — config, progress tracking, and
//! batch execution logic live in backbone-core.

use backbone_core::GenericBulkService;
pub use backbone_core::{BulkOperationConfig, BulkOperationProgress, BulkFailureMode, BulkItemResult, BulkOperationResult};

use crate::presentation::dto::CreateTimeoffRequestDto;
use crate::application::service::TimeoffRequestService;
use crate::domain::entity::TimeoffRequest;

/// Bulk operation handler for TimeoffRequest entities.
///
/// Wraps `TimeoffRequestService` with configurable batch size, concurrency,
/// and `ContinueOnError` / `AbortOnFirstError` failure modes.
pub type TimeoffRequestBulkService = GenericBulkService<TimeoffRequest, CreateTimeoffRequestDto, TimeoffRequestService>;

// <<< CUSTOM
// END CUSTOM
