//! Bulk operations for TimeoffBalance entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericBulkService` — config, progress tracking, and
//! batch execution logic live in backbone-core.

use backbone_core::GenericBulkService;
pub use backbone_core::{BulkOperationConfig, BulkOperationProgress, BulkFailureMode, BulkItemResult, BulkOperationResult};

use crate::presentation::dto::CreateTimeoffBalanceDto;
use crate::application::service::TimeoffBalanceService;
use crate::domain::entity::TimeoffBalance;

/// Bulk operation handler for TimeoffBalance entities.
///
/// Wraps `TimeoffBalanceService` with configurable batch size, concurrency,
/// and `ContinueOnError` / `AbortOnFirstError` failure modes.
pub type TimeoffBalanceBulkService = GenericBulkService<TimeoffBalance, CreateTimeoffBalanceDto, TimeoffBalanceService>;

// <<< CUSTOM
// END CUSTOM
