//! Bulk operations for TimeoffType entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericBulkService` — config, progress tracking, and
//! batch execution logic live in backbone-core.

use backbone_core::GenericBulkService;
pub use backbone_core::{BulkOperationConfig, BulkOperationProgress, BulkFailureMode, BulkItemResult, BulkOperationResult};

use crate::presentation::dto::CreateTimeoffTypeDto;
use crate::application::service::TimeoffTypeService;
use crate::domain::entity::TimeoffType;

/// Bulk operation handler for TimeoffType entities.
///
/// Wraps `TimeoffTypeService` with configurable batch size, concurrency,
/// and `ContinueOnError` / `AbortOnFirstError` failure modes.
pub type TimeoffTypeBulkService = GenericBulkService<TimeoffType, CreateTimeoffTypeDto, TimeoffTypeService>;

// <<< CUSTOM
// END CUSTOM
