//! TimeoffAccrualLevel DTOs (Data Transfer Objects)
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc};
use rust_decimal::Decimal;

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::TimeoffAccrualLevel;
use crate::domain::entity::AuditMetadata;
use crate::domain::entity::AccrualFrequency;
use crate::domain::entity::AccrualLostDaysAction;
use crate::domain::entity::AccrualStartType;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new TimeoffAccrualLevel
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateTimeoffAccrualLevelDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "plan_id")]
    pub plan_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    pub sequence: i32,
    #[serde(alias = "start_count")]
    pub start_count: Decimal,
    #[serde(alias = "start_type")]
    pub start_type: AccrualStartType,
    pub frequency: AccrualFrequency,
    #[serde(alias = "added_value")]
    pub added_value: Decimal,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(alias = "is_added_based_on_worked_time")]
    pub is_added_based_on_worked_time: bool,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "maximum_leave")]
    pub maximum_leave: Option<Decimal>,
    #[serde(alias = "action_with_lost_days")]
    pub action_with_lost_days: AccrualLostDaysAction,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "postponed_max_days")]
    pub postponed_max_days: Option<Decimal>,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a TimeoffAccrualLevel
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateTimeoffAccrualLevelDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "plan_id")]
    pub plan_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    pub sequence: i32,
    #[serde(alias = "start_count")]
    pub start_count: Decimal,
    #[serde(alias = "start_type")]
    pub start_type: AccrualStartType,
    pub frequency: AccrualFrequency,
    #[serde(alias = "added_value")]
    pub added_value: Decimal,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(alias = "is_added_based_on_worked_time")]
    pub is_added_based_on_worked_time: bool,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "maximum_leave")]
    pub maximum_leave: Option<Decimal>,
    #[serde(alias = "action_with_lost_days")]
    pub action_with_lost_days: AccrualLostDaysAction,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "postponed_max_days")]
    pub postponed_max_days: Option<Decimal>,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a TimeoffAccrualLevel
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchTimeoffAccrualLevelDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "plan_id")]
    pub plan_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub sequence: Option<i32>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "start_count")]
    pub start_count: Option<Decimal>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "start_type")]
    pub start_type: Option<AccrualStartType>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub frequency: Option<AccrualFrequency>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "added_value")]
    pub added_value: Option<Decimal>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "is_added_based_on_worked_time")]
    pub is_added_based_on_worked_time: Option<bool>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "maximum_leave")]
    pub maximum_leave: Option<Decimal>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "action_with_lost_days")]
    pub action_with_lost_days: Option<AccrualLostDaysAction>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "postponed_max_days")]
    pub postponed_max_days: Option<Decimal>,
}

impl PatchTimeoffAccrualLevelDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.plan_id.is_some() || self.sequence.is_some() || self.start_count.is_some() || self.start_type.is_some() || self.frequency.is_some() || self.added_value.is_some() || self.is_added_based_on_worked_time.is_some() || self.maximum_leave.is_some() || self.action_with_lost_days.is_some() || self.postponed_max_days.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for TimeoffAccrualLevel entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct TimeoffAccrualLevelResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub plan_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    pub sequence: i32,
    pub start_count: Decimal,
    pub start_type: AccrualStartType,
    pub frequency: AccrualFrequency,
    pub added_value: Decimal,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub is_added_based_on_worked_time: bool,
    pub maximum_leave: Option<Decimal>,
    pub action_with_lost_days: AccrualLostDaysAction,
    pub postponed_max_days: Option<Decimal>,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for TimeoffAccrualLevel entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct TimeoffAccrualLevelListResponseDto {
    /// List of items
    pub items: Vec<TimeoffAccrualLevelResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl TimeoffAccrualLevelListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<TimeoffAccrualLevelResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct TimeoffAccrualLevelSummaryDto {
    pub id: Uuid,
    pub plan_id: Uuid,
    pub sequence: i32,
    pub start_count: Decimal,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<TimeoffAccrualLevel> for TimeoffAccrualLevelResponseDto {
    fn from(entity: TimeoffAccrualLevel) -> Self {
        Self {
            id: entity.id,
            plan_id: entity.plan_id,
            sequence: entity.sequence,
            start_count: entity.start_count,
            start_type: entity.start_type,
            frequency: entity.frequency,
            added_value: entity.added_value,
            is_added_based_on_worked_time: entity.is_added_based_on_worked_time,
            maximum_leave: entity.maximum_leave,
            action_with_lost_days: entity.action_with_lost_days,
            postponed_max_days: entity.postponed_max_days,
            metadata: entity.metadata,
        }
    }
}

impl From<TimeoffAccrualLevel> for TimeoffAccrualLevelSummaryDto {
    fn from(entity: TimeoffAccrualLevel) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            plan_id: entity.plan_id,
            sequence: entity.sequence,
            start_count: entity.start_count,
            created_at,
        }
    }
}

impl From<CreateTimeoffAccrualLevelDto> for TimeoffAccrualLevel {
    fn from(dto: CreateTimeoffAccrualLevelDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            plan_id: dto.plan_id,
            sequence: dto.sequence,
            start_count: dto.start_count,
            start_type: dto.start_type,
            frequency: dto.frequency,
            added_value: dto.added_value,
            is_added_based_on_worked_time: dto.is_added_based_on_worked_time,
            maximum_leave: dto.maximum_leave,
            action_with_lost_days: dto.action_with_lost_days,
            postponed_max_days: dto.postponed_max_days,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&TimeoffAccrualLevel> for TimeoffAccrualLevelResponseDto {
    fn from(entity: &TimeoffAccrualLevel) -> Self {
        Self {
            id: entity.id.clone(),
            plan_id: entity.plan_id.clone(),
            sequence: entity.sequence.clone(),
            start_count: entity.start_count.clone(),
            start_type: entity.start_type.clone(),
            frequency: entity.frequency.clone(),
            added_value: entity.added_value.clone(),
            is_added_based_on_worked_time: entity.is_added_based_on_worked_time.clone(),
            maximum_leave: entity.maximum_leave.clone(),
            action_with_lost_days: entity.action_with_lost_days.clone(),
            postponed_max_days: entity.postponed_max_days.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateTimeoffAccrualLevelDto> for TimeoffAccrualLevel {
    fn from_create_dto(dto: CreateTimeoffAccrualLevelDto) -> backbone_core::ServiceResult<Self> {
        Ok(TimeoffAccrualLevel::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateTimeoffAccrualLevelDto> for TimeoffAccrualLevel {
    fn apply_update(mut self, dto: UpdateTimeoffAccrualLevelDto) -> backbone_core::ServiceResult<Self> {
        self.plan_id = dto.plan_id;
        self.sequence = dto.sequence;
        self.start_count = dto.start_count;
        self.start_type = dto.start_type;
        self.frequency = dto.frequency;
        self.added_value = dto.added_value;
        self.is_added_based_on_worked_time = dto.is_added_based_on_worked_time;
        self.maximum_leave = dto.maximum_leave;
        self.action_with_lost_days = dto.action_with_lost_days;
        self.postponed_max_days = dto.postponed_max_days;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to TimeoffAccrualLevel here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs
