//! TimeoffType DTOs (Data Transfer Objects)
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc};

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::TimeoffType;
use crate::domain::entity::AuditMetadata;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new TimeoffType
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateTimeoffTypeDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    #[cfg_attr(feature = "validation", validate(length(max = 120)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub name: String,
    #[cfg_attr(feature = "validation", validate(length(max = 40)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub code: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(alias = "is_paid")]
    pub is_paid: bool,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(alias = "allow_carry_forward")]
    pub allow_carry_forward: bool,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a TimeoffType
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateTimeoffTypeDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    #[cfg_attr(feature = "validation", validate(length(max = 120)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub name: String,
    #[cfg_attr(feature = "validation", validate(length(max = 40)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub code: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(alias = "is_paid")]
    pub is_paid: bool,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(alias = "allow_carry_forward")]
    pub allow_carry_forward: bool,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a TimeoffType
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchTimeoffTypeDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "company_id")]
    pub company_id: Option<Uuid>,
    #[cfg_attr(feature = "validation", validate(length(max = 120)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 40)))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub code: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "is_paid")]
    pub is_paid: Option<bool>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "allow_carry_forward")]
    pub allow_carry_forward: Option<bool>,
}

impl PatchTimeoffTypeDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.company_id.is_some() || self.name.is_some() || self.code.is_some() || self.is_paid.is_some() || self.allow_carry_forward.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for TimeoffType entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct TimeoffTypeResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub name: String,
    pub code: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub is_paid: bool,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub allow_carry_forward: bool,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for TimeoffType entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct TimeoffTypeListResponseDto {
    /// List of items
    pub items: Vec<TimeoffTypeResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl TimeoffTypeListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<TimeoffTypeResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct TimeoffTypeSummaryDto {
    pub id: Uuid,
    pub company_id: Uuid,
    pub name: String,
    pub code: Option<String>,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<TimeoffType> for TimeoffTypeResponseDto {
    fn from(entity: TimeoffType) -> Self {
        Self {
            id: entity.id,
            company_id: entity.company_id,
            name: entity.name,
            code: entity.code,
            is_paid: entity.is_paid,
            allow_carry_forward: entity.allow_carry_forward,
            metadata: entity.metadata,
        }
    }
}

impl From<TimeoffType> for TimeoffTypeSummaryDto {
    fn from(entity: TimeoffType) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            company_id: entity.company_id,
            name: entity.name,
            code: entity.code,
            created_at,
        }
    }
}

impl From<CreateTimeoffTypeDto> for TimeoffType {
    fn from(dto: CreateTimeoffTypeDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            company_id: dto.company_id,
            name: dto.name,
            code: dto.code,
            is_paid: dto.is_paid,
            allow_carry_forward: dto.allow_carry_forward,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&TimeoffType> for TimeoffTypeResponseDto {
    fn from(entity: &TimeoffType) -> Self {
        Self {
            id: entity.id.clone(),
            company_id: entity.company_id.clone(),
            name: entity.name.clone(),
            code: entity.code.clone(),
            is_paid: entity.is_paid.clone(),
            allow_carry_forward: entity.allow_carry_forward.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateTimeoffTypeDto> for TimeoffType {
    fn from_create_dto(dto: CreateTimeoffTypeDto) -> backbone_core::ServiceResult<Self> {
        Ok(TimeoffType::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateTimeoffTypeDto> for TimeoffType {
    fn apply_update(mut self, dto: UpdateTimeoffTypeDto) -> backbone_core::ServiceResult<Self> {
        self.company_id = dto.company_id;
        self.name = dto.name;
        self.code = dto.code;
        self.is_paid = dto.is_paid;
        self.allow_carry_forward = dto.allow_carry_forward;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to TimeoffType here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs

