//! TimeoffRequest DTOs (Data Transfer Objects)
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc, NaiveDate};

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::TimeoffRequest;
use crate::domain::entity::AuditMetadata;
use crate::domain::entity::TimeoffRequestStatus;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new TimeoffRequest
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateTimeoffRequestDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "timeoff_type_id")]
    pub timeoff_type_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "employee_id")]
    pub employee_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01"))]
    #[serde(alias = "date_start")]
    pub date_start: NaiveDate,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01"))]
    #[serde(alias = "date_end")]
    pub date_end: NaiveDate,
    #[cfg_attr(feature = "validation", validate(length(max = 1000)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub note: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "approval_employee_id")]
    pub approval_employee_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "approval_request_id")]
    pub approval_request_id: Option<Uuid>,
    #[cfg_attr(feature = "validation", validate(length(max = 1000)))]
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "note_reject")]
    pub note_reject: Option<String>,
    pub status: TimeoffRequestStatus,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a TimeoffRequest
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateTimeoffRequestDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "timeoff_type_id")]
    pub timeoff_type_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "employee_id")]
    pub employee_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01"))]
    #[serde(alias = "date_start")]
    pub date_start: NaiveDate,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01"))]
    #[serde(alias = "date_end")]
    pub date_end: NaiveDate,
    #[cfg_attr(feature = "validation", validate(length(max = 1000)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub note: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "approval_employee_id")]
    pub approval_employee_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "approval_request_id")]
    pub approval_request_id: Option<Uuid>,
    #[cfg_attr(feature = "validation", validate(length(max = 1000)))]
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "note_reject")]
    pub note_reject: Option<String>,
    pub status: TimeoffRequestStatus,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a TimeoffRequest
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchTimeoffRequestDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "timeoff_type_id")]
    pub timeoff_type_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "employee_id")]
    pub employee_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "date_start")]
    pub date_start: Option<NaiveDate>,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "date_end")]
    pub date_end: Option<NaiveDate>,
    #[cfg_attr(feature = "validation", validate(length(max = 1000)))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub note: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "approval_employee_id")]
    pub approval_employee_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "approval_request_id")]
    pub approval_request_id: Option<Uuid>,
    #[cfg_attr(feature = "validation", validate(length(max = 1000)))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "note_reject")]
    pub note_reject: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub status: Option<TimeoffRequestStatus>,
}

impl PatchTimeoffRequestDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.timeoff_type_id.is_some() || self.employee_id.is_some() || self.date_start.is_some() || self.date_end.is_some() || self.note.is_some() || self.approval_employee_id.is_some() || self.approval_request_id.is_some() || self.note_reject.is_some() || self.status.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for TimeoffRequest entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct TimeoffRequestResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub timeoff_type_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub employee_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01"))]
    pub date_start: NaiveDate,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01"))]
    pub date_end: NaiveDate,
    pub note: Option<String>,
    pub approval_employee_id: Option<Uuid>,
    pub approval_request_id: Option<Uuid>,
    pub note_reject: Option<String>,
    pub status: TimeoffRequestStatus,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for TimeoffRequest entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct TimeoffRequestListResponseDto {
    /// List of items
    pub items: Vec<TimeoffRequestResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl TimeoffRequestListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<TimeoffRequestResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct TimeoffRequestSummaryDto {
    pub id: Uuid,
    pub timeoff_type_id: Uuid,
    pub employee_id: Uuid,
    pub date_start: NaiveDate,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<TimeoffRequest> for TimeoffRequestResponseDto {
    fn from(entity: TimeoffRequest) -> Self {
        Self {
            id: entity.id,
            timeoff_type_id: entity.timeoff_type_id,
            employee_id: entity.employee_id,
            date_start: entity.date_start,
            date_end: entity.date_end,
            note: entity.note,
            approval_employee_id: entity.approval_employee_id,
            approval_request_id: entity.approval_request_id,
            note_reject: entity.note_reject,
            status: entity.status,
            metadata: entity.metadata,
        }
    }
}

impl From<TimeoffRequest> for TimeoffRequestSummaryDto {
    fn from(entity: TimeoffRequest) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            timeoff_type_id: entity.timeoff_type_id,
            employee_id: entity.employee_id,
            date_start: entity.date_start,
            created_at,
        }
    }
}

impl From<CreateTimeoffRequestDto> for TimeoffRequest {
    fn from(dto: CreateTimeoffRequestDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            timeoff_type_id: dto.timeoff_type_id,
            employee_id: dto.employee_id,
            date_start: dto.date_start,
            date_end: dto.date_end,
            note: dto.note,
            approval_employee_id: dto.approval_employee_id,
            approval_request_id: dto.approval_request_id,
            note_reject: dto.note_reject,
            status: dto.status,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&TimeoffRequest> for TimeoffRequestResponseDto {
    fn from(entity: &TimeoffRequest) -> Self {
        Self {
            id: entity.id.clone(),
            timeoff_type_id: entity.timeoff_type_id.clone(),
            employee_id: entity.employee_id.clone(),
            date_start: entity.date_start.clone(),
            date_end: entity.date_end.clone(),
            note: entity.note.clone(),
            approval_employee_id: entity.approval_employee_id.clone(),
            approval_request_id: entity.approval_request_id.clone(),
            note_reject: entity.note_reject.clone(),
            status: entity.status.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateTimeoffRequestDto> for TimeoffRequest {
    fn from_create_dto(dto: CreateTimeoffRequestDto) -> backbone_core::ServiceResult<Self> {
        Ok(TimeoffRequest::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateTimeoffRequestDto> for TimeoffRequest {
    fn apply_update(mut self, dto: UpdateTimeoffRequestDto) -> backbone_core::ServiceResult<Self> {
        self.timeoff_type_id = dto.timeoff_type_id;
        self.employee_id = dto.employee_id;
        self.date_start = dto.date_start;
        self.date_end = dto.date_end;
        self.note = dto.note;
        self.approval_employee_id = dto.approval_employee_id;
        self.approval_request_id = dto.approval_request_id;
        self.note_reject = dto.note_reject;
        self.status = dto.status;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to TimeoffRequest here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs
