//! TimeoffAccrualPlan DTOs (Data Transfer Objects)
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc};

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::TimeoffAccrualPlan;
use crate::domain::entity::AuditMetadata;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new TimeoffAccrualPlan
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateTimeoffAccrualPlanDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "timeoff_type_id")]
    pub timeoff_type_id: Uuid,
    #[cfg_attr(feature = "validation", validate(length(max = 120)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub name: String,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a TimeoffAccrualPlan
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateTimeoffAccrualPlanDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "timeoff_type_id")]
    pub timeoff_type_id: Uuid,
    #[cfg_attr(feature = "validation", validate(length(max = 120)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub name: String,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a TimeoffAccrualPlan
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchTimeoffAccrualPlanDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "timeoff_type_id")]
    pub timeoff_type_id: Option<Uuid>,
    #[cfg_attr(feature = "validation", validate(length(max = 120)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
}

impl PatchTimeoffAccrualPlanDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.timeoff_type_id.is_some() || self.name.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for TimeoffAccrualPlan entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct TimeoffAccrualPlanResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub timeoff_type_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub name: String,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for TimeoffAccrualPlan entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct TimeoffAccrualPlanListResponseDto {
    /// List of items
    pub items: Vec<TimeoffAccrualPlanResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl TimeoffAccrualPlanListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<TimeoffAccrualPlanResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct TimeoffAccrualPlanSummaryDto {
    pub id: Uuid,
    pub timeoff_type_id: Uuid,
    pub name: String,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<TimeoffAccrualPlan> for TimeoffAccrualPlanResponseDto {
    fn from(entity: TimeoffAccrualPlan) -> Self {
        Self {
            id: entity.id,
            timeoff_type_id: entity.timeoff_type_id,
            name: entity.name,
            metadata: entity.metadata,
        }
    }
}

impl From<TimeoffAccrualPlan> for TimeoffAccrualPlanSummaryDto {
    fn from(entity: TimeoffAccrualPlan) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            timeoff_type_id: entity.timeoff_type_id,
            name: entity.name,
            created_at,
        }
    }
}

impl From<CreateTimeoffAccrualPlanDto> for TimeoffAccrualPlan {
    fn from(dto: CreateTimeoffAccrualPlanDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            timeoff_type_id: dto.timeoff_type_id,
            name: dto.name,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&TimeoffAccrualPlan> for TimeoffAccrualPlanResponseDto {
    fn from(entity: &TimeoffAccrualPlan) -> Self {
        Self {
            id: entity.id.clone(),
            timeoff_type_id: entity.timeoff_type_id.clone(),
            name: entity.name.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateTimeoffAccrualPlanDto> for TimeoffAccrualPlan {
    fn from_create_dto(dto: CreateTimeoffAccrualPlanDto) -> backbone_core::ServiceResult<Self> {
        Ok(TimeoffAccrualPlan::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateTimeoffAccrualPlanDto> for TimeoffAccrualPlan {
    fn apply_update(mut self, dto: UpdateTimeoffAccrualPlanDto) -> backbone_core::ServiceResult<Self> {
        self.timeoff_type_id = dto.timeoff_type_id;
        self.name = dto.name;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to TimeoffAccrualPlan here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs
