//! TimeoffBalance DTOs (Data Transfer Objects)
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc};
use rust_decimal::Decimal;

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::TimeoffBalance;
use crate::domain::entity::AuditMetadata;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new TimeoffBalance
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateTimeoffBalanceDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "timeoff_type_id")]
    pub timeoff_type_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "employee_id")]
    pub employee_id: Uuid,
    #[cfg_attr(feature = "validation", validate(length(max = 10)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub period: String,
    pub allocated: Decimal,
    pub used: Decimal,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a TimeoffBalance
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateTimeoffBalanceDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "timeoff_type_id")]
    pub timeoff_type_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "employee_id")]
    pub employee_id: Uuid,
    #[cfg_attr(feature = "validation", validate(length(max = 10)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub period: String,
    pub allocated: Decimal,
    pub used: Decimal,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a TimeoffBalance
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchTimeoffBalanceDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "company_id")]
    pub company_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "timeoff_type_id")]
    pub timeoff_type_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "employee_id")]
    pub employee_id: Option<Uuid>,
    #[cfg_attr(feature = "validation", validate(length(max = 10)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub period: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub allocated: Option<Decimal>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub used: Option<Decimal>,
}

impl PatchTimeoffBalanceDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.company_id.is_some() || self.timeoff_type_id.is_some() || self.employee_id.is_some() || self.period.is_some() || self.allocated.is_some() || self.used.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for TimeoffBalance entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct TimeoffBalanceResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub timeoff_type_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub employee_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub period: String,
    pub allocated: Decimal,
    pub used: Decimal,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for TimeoffBalance entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct TimeoffBalanceListResponseDto {
    /// List of items
    pub items: Vec<TimeoffBalanceResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl TimeoffBalanceListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<TimeoffBalanceResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct TimeoffBalanceSummaryDto {
    pub id: Uuid,
    pub company_id: Uuid,
    pub timeoff_type_id: Uuid,
    pub employee_id: Uuid,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<TimeoffBalance> for TimeoffBalanceResponseDto {
    fn from(entity: TimeoffBalance) -> Self {
        Self {
            id: entity.id,
            company_id: entity.company_id,
            timeoff_type_id: entity.timeoff_type_id,
            employee_id: entity.employee_id,
            period: entity.period,
            allocated: entity.allocated,
            used: entity.used,
            metadata: entity.metadata,
        }
    }
}

impl From<TimeoffBalance> for TimeoffBalanceSummaryDto {
    fn from(entity: TimeoffBalance) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            company_id: entity.company_id,
            timeoff_type_id: entity.timeoff_type_id,
            employee_id: entity.employee_id,
            created_at,
        }
    }
}

impl From<CreateTimeoffBalanceDto> for TimeoffBalance {
    fn from(dto: CreateTimeoffBalanceDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            company_id: dto.company_id,
            timeoff_type_id: dto.timeoff_type_id,
            employee_id: dto.employee_id,
            period: dto.period,
            allocated: dto.allocated,
            used: dto.used,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&TimeoffBalance> for TimeoffBalanceResponseDto {
    fn from(entity: &TimeoffBalance) -> Self {
        Self {
            id: entity.id.clone(),
            company_id: entity.company_id.clone(),
            timeoff_type_id: entity.timeoff_type_id.clone(),
            employee_id: entity.employee_id.clone(),
            period: entity.period.clone(),
            allocated: entity.allocated.clone(),
            used: entity.used.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateTimeoffBalanceDto> for TimeoffBalance {
    fn from_create_dto(dto: CreateTimeoffBalanceDto) -> backbone_core::ServiceResult<Self> {
        Ok(TimeoffBalance::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateTimeoffBalanceDto> for TimeoffBalance {
    fn apply_update(mut self, dto: UpdateTimeoffBalanceDto) -> backbone_core::ServiceResult<Self> {
        self.company_id = dto.company_id;
        self.timeoff_type_id = dto.timeoff_type_id;
        self.employee_id = dto.employee_id;
        self.period = dto.period;
        self.allocated = dto.allocated;
        self.used = dto.used;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to TimeoffBalance here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs

