//! Domain policies
//!
//! Generated by metaphor-schema. Do not edit manually.

pub mod timeoff_balance_domain_policy;
pub mod timeoff_request_domain_policy;
pub mod timeoff_type_domain_policy;

pub use timeoff_balance_domain_policy::TimeoffBalanceDomainPolicy;
pub use timeoff_request_domain_policy::TimeoffRequestDomainPolicy;
pub use timeoff_type_domain_policy::TimeoffTypeDomainPolicy;

// <<< CUSTOM
// END CUSTOM
