//! Application services
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each entity service is a type alias over `GenericCrudService`.

pub mod error;
pub use error::{ServiceError, ServiceResult};

pub mod timeoff_balance_service;
pub mod timeoff_request_service;
pub mod timeoff_type_service;

// <<< CUSTOM
// Hand-written `TimeoffQueryService` impl for `TimeoffModule` — the seam every other module consumes
// timeoff through. Standard lookups delegate to the CRUD services; `paid_leave_days` delegates to
// `TimeoffRequestRepository::paid_leave_days` (custom SQL on the repo).
pub mod timeoff_query_service;
// Hand-authored leave-drawdown write service — `approve_request` / `reject_request` / `cancel_request`
// with tx-gated balance draw + restore. Ported verbatim from backbone-hr's `hr_write_service.rs`.
pub mod timeoff_request_service_custom;
pub use timeoff_request_service_custom::{TimeoffError, TimeoffRequestWriteService};
// ADR-005 consumer: the timeoff-side receiver for the `offboarding.closed` compound event. Zeroes the
// leaver's remaining leave balance (paid out via payroll's OffboardingSettlementHandler) idempotently
// (inbox dedup on the envelope id). Registered on the integration bus in backbone-hr-app's main.rs.
pub mod offboarding_encash_handler;
// END CUSTOM

pub use timeoff_balance_service::TimeoffBalanceService;
pub use timeoff_request_service::TimeoffRequestService;
pub use timeoff_type_service::TimeoffTypeService;
// <<< CUSTOM
pub use offboarding_encash_handler::OffboardingEncashHandler;
// END CUSTOM
