//! Application service for TimeoffRequest entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `timeoff_request_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreateTimeoffRequestDto, UpdateTimeoffRequestDto};
use crate::domain::entity::TimeoffRequest;
use crate::infrastructure::persistence::TimeoffRequestRepository;

/// Application service for TimeoffRequest entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `timeoff_request_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct TimeoffRequestServiceCustom {
///     inner: Arc<TimeoffRequestService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type TimeoffRequestService = GenericCrudService<
    TimeoffRequest,
    CreateTimeoffRequestDto,
    UpdateTimeoffRequestDto,
    TimeoffRequestRepository,
>;

// <<< CUSTOM
// END CUSTOM
