//! Application service for TimeoffType entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `timeoff_type_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreateTimeoffTypeDto, UpdateTimeoffTypeDto};
use crate::domain::entity::TimeoffType;
use crate::infrastructure::persistence::TimeoffTypeRepository;

/// Application service for TimeoffType entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `timeoff_type_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct TimeoffTypeServiceCustom {
///     inner: Arc<TimeoffTypeService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type TimeoffTypeService = GenericCrudService<
    TimeoffType,
    CreateTimeoffTypeDto,
    UpdateTimeoffTypeDto,
    TimeoffTypeRepository,
>;

// <<< CUSTOM
// END CUSTOM
