//! Application service for TimeoffAccrualLevel entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `timeoff_accrual_level_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreateTimeoffAccrualLevelDto, UpdateTimeoffAccrualLevelDto};
use crate::domain::entity::TimeoffAccrualLevel;
use crate::infrastructure::persistence::TimeoffAccrualLevelRepository;

/// Application service for TimeoffAccrualLevel entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `timeoff_accrual_level_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct TimeoffAccrualLevelServiceCustom {
///     inner: Arc<TimeoffAccrualLevelService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type TimeoffAccrualLevelService = GenericCrudService<
    TimeoffAccrualLevel,
    CreateTimeoffAccrualLevelDto,
    UpdateTimeoffAccrualLevelDto,
    TimeoffAccrualLevelRepository,
>;

// <<< CUSTOM
// END CUSTOM
