//! Application service for TimeoffBalance entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `timeoff_balance_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreateTimeoffBalanceDto, UpdateTimeoffBalanceDto};
use crate::domain::entity::TimeoffBalance;
use crate::infrastructure::persistence::TimeoffBalanceRepository;

/// Application service for TimeoffBalance entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `timeoff_balance_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct TimeoffBalanceServiceCustom {
///     inner: Arc<TimeoffBalanceService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type TimeoffBalanceService = GenericCrudService<
    TimeoffBalance,
    CreateTimeoffBalanceDto,
    UpdateTimeoffBalanceDto,
    TimeoffBalanceRepository,
>;

// <<< CUSTOM
// END CUSTOM
