//! Application service for TimeoffAccrualPlan entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `timeoff_accrual_plan_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreateTimeoffAccrualPlanDto, UpdateTimeoffAccrualPlanDto};
use crate::domain::entity::TimeoffAccrualPlan;
use crate::infrastructure::persistence::TimeoffAccrualPlanRepository;

/// Application service for TimeoffAccrualPlan entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `timeoff_accrual_plan_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct TimeoffAccrualPlanServiceCustom {
///     inner: Arc<TimeoffAccrualPlanService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type TimeoffAccrualPlanService = GenericCrudService<
    TimeoffAccrualPlan,
    CreateTimeoffAccrualPlanDto,
    UpdateTimeoffAccrualPlanDto,
    TimeoffAccrualPlanRepository,
>;

// <<< CUSTOM
// END CUSTOM
