-- TimeoffAccrualLevel Seed Data
-- Generated by metaphor-schema
--
-- This file contains initial seed data for the timeoff.timeoff_accrual_levels table.
-- Customize this file to add your initial data.

-- INSERT INTO timeoff.timeoff_accrual_levels (
--     id,
--     company_id,
--     plan_id,
--     sequence,
--     start_count,
--     start_type,
--     frequency,
--     added_value,
--     is_added_based_on_worked_time,
--     maximum_leave,
--     action_with_lost_days,
--     postponed_max_days,
--     metadata
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert test data
-- Uncomment and modify the following for development/testing:

-- INSERT INTO timeoff.timeoff_accrual_levels (id, created_at, updated_at) VALUES
--     (gen_random_uuid(), NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

