-- Migration: Create timeoff_accrual_levels table
-- Generated by metaphor-schema

-- Create accrual_start_type enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'accrual_start_type') THEN
        CREATE TYPE accrual_start_type AS ENUM ('days', 'months', 'years');
    END IF;
END
$$;

-- Create accrual_frequency enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'accrual_frequency') THEN
        CREATE TYPE accrual_frequency AS ENUM ('daily', 'weekly', 'biweekly', 'monthly', 'bimonthly', 'quarterly', 'yearly', 'once');
    END IF;
END
$$;

-- Create accrual_lost_days_action enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'accrual_lost_days_action') THEN
        CREATE TYPE accrual_lost_days_action AS ENUM ('nothing', 'postponed_to_next_accrual');
    END IF;
END
$$;

CREATE SCHEMA IF NOT EXISTS timeoff;

CREATE TABLE IF NOT EXISTS timeoff.timeoff_accrual_levels (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    company_id UUID NOT NULL,
    plan_id UUID NOT NULL,
    sequence INTEGER NOT NULL,
    start_count NUMERIC(18, 2) NOT NULL DEFAULT 0 CHECK (start_count >= 0),
    start_type accrual_start_type NOT NULL DEFAULT 'years',
    frequency accrual_frequency NOT NULL DEFAULT 'monthly',
    added_value NUMERIC(18, 2) NOT NULL CHECK (added_value >= 0),
    is_added_based_on_worked_time BOOLEAN NOT NULL DEFAULT FALSE,
    maximum_leave NUMERIC(18, 2) CHECK (maximum_leave >= 0),
    action_with_lost_days accrual_lost_days_action NOT NULL DEFAULT 'nothing',
    postponed_max_days NUMERIC(18, 2) CHECK (postponed_max_days >= 0),
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_timeoff_accrual_levels_plan_id_sequence ON timeoff.timeoff_accrual_levels (plan_id, sequence) WHERE (metadata->>'deleted_at') IS NULL;

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_timeoff_accrual_levels_metadata_gin ON timeoff.timeoff_accrual_levels USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_timeoff_accrual_levels_metadata_deleted_at ON timeoff.timeoff_accrual_levels ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_timeoff_accrual_levels_metadata_created_at ON timeoff.timeoff_accrual_levels ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_timeoff_accrual_levels_metadata_updated_at ON timeoff.timeoff_accrual_levels ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION timeoff.timeoff_accrual_levels_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS timeoff_accrual_levels_insert_audit ON timeoff.timeoff_accrual_levels;
CREATE TRIGGER timeoff_accrual_levels_insert_audit BEFORE INSERT ON timeoff.timeoff_accrual_levels
    FOR EACH ROW EXECUTE FUNCTION timeoff.timeoff_accrual_levels_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS timeoff_accrual_levels_update_audit ON timeoff.timeoff_accrual_levels;
CREATE TRIGGER timeoff_accrual_levels_update_audit BEFORE UPDATE ON timeoff.timeoff_accrual_levels
    FOR EACH ROW EXECUTE FUNCTION timeoff.timeoff_accrual_levels_audit_timestamp();
