-- Enum types for timeoff module
-- Generated by metaphor-schema

-- Create timeoff_request_status enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'timeoff_request_status') THEN
        CREATE TYPE timeoff_request_status AS ENUM ('pending', 'approved', 'rejected', 'cancelled');
    END IF;
END
$$;

