-- Company RLS fence for timeoff module (ADR-0008)
-- Generated by metaphor-schema. Requires the app to connect as a
-- non-superuser role; migrations/seeders run as the owner and bypass.

-- Migration: company row-level-security fence for timeoff.timeoff_balances
-- Generated by metaphor-schema (ADR-0008). company_id is scoped per request
-- via `set_config('app.company_id', <uuid>, true)`; an unset var sees zero rows.

ALTER TABLE timeoff.timeoff_balances ENABLE ROW LEVEL SECURITY;
ALTER TABLE timeoff.timeoff_balances FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS timeoff_balances_company_isolation ON timeoff.timeoff_balances;
CREATE POLICY timeoff_balances_company_isolation ON timeoff.timeoff_balances
    FOR ALL
    USING      (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid)
    WITH CHECK (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid);

-- Migration: company row-level-security fence for timeoff.timeoff_requests
-- Generated by metaphor-schema (ADR-0008). company_id is scoped per request
-- via `set_config('app.company_id', <uuid>, true)`; an unset var sees zero rows.

ALTER TABLE timeoff.timeoff_requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE timeoff.timeoff_requests FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS timeoff_requests_company_isolation ON timeoff.timeoff_requests;
CREATE POLICY timeoff_requests_company_isolation ON timeoff.timeoff_requests
    FOR ALL
    USING      (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid)
    WITH CHECK (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid);

-- Migration: company row-level-security fence for timeoff.timeoff_types
-- Generated by metaphor-schema (ADR-0008). company_id is scoped per request
-- via `set_config('app.company_id', <uuid>, true)`; an unset var sees zero rows.

ALTER TABLE timeoff.timeoff_types ENABLE ROW LEVEL SECURITY;
ALTER TABLE timeoff.timeoff_types FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS timeoff_types_company_isolation ON timeoff.timeoff_types;
CREATE POLICY timeoff_types_company_isolation ON timeoff.timeoff_types
    FOR ALL
    USING      (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid)
    WITH CHECK (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid);

