-- Migration: Create timeoff_accrual_plans table
-- Generated by metaphor-schema

CREATE SCHEMA IF NOT EXISTS timeoff;

CREATE TABLE IF NOT EXISTS timeoff.timeoff_accrual_plans (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    company_id UUID NOT NULL,
    timeoff_type_id UUID NOT NULL,
    name TEXT NOT NULL,
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_timeoff_accrual_plans_company_id_timeoff_type_id ON timeoff.timeoff_accrual_plans (company_id, timeoff_type_id);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_timeoff_accrual_plans_metadata_gin ON timeoff.timeoff_accrual_plans USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_timeoff_accrual_plans_metadata_deleted_at ON timeoff.timeoff_accrual_plans ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_timeoff_accrual_plans_metadata_created_at ON timeoff.timeoff_accrual_plans ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_timeoff_accrual_plans_metadata_updated_at ON timeoff.timeoff_accrual_plans ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION timeoff.timeoff_accrual_plans_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS timeoff_accrual_plans_insert_audit ON timeoff.timeoff_accrual_plans;
CREATE TRIGGER timeoff_accrual_plans_insert_audit BEFORE INSERT ON timeoff.timeoff_accrual_plans
    FOR EACH ROW EXECUTE FUNCTION timeoff.timeoff_accrual_plans_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS timeoff_accrual_plans_update_audit ON timeoff.timeoff_accrual_plans;
CREATE TRIGGER timeoff_accrual_plans_update_audit BEFORE UPDATE ON timeoff.timeoff_accrual_plans
    FOR EACH ROW EXECUTE FUNCTION timeoff.timeoff_accrual_plans_audit_timestamp();
