-- Audit Triggers Migration for timeoff module
-- Generated by metaphor-schema
--
-- This migration adds automatic timestamp management triggers
-- to all tables with audit metadata fields.
--
-- Triggers automatically set:
--   - metadata->'created_at' on INSERT
--   - metadata->'updated_at' on INSERT and UPDATE

-- ==============================================================================
-- Table: TimeoffBalance (timeoff.timeoff_balances)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION timeoff.timeoff_balances_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS timeoff_balances_insert_audit ON timeoff.timeoff_balances;
CREATE TRIGGER timeoff_balances_insert_audit BEFORE INSERT ON timeoff.timeoff_balances
    FOR EACH ROW EXECUTE FUNCTION timeoff.timeoff_balances_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS timeoff_balances_update_audit ON timeoff.timeoff_balances;
CREATE TRIGGER timeoff_balances_update_audit BEFORE UPDATE ON timeoff.timeoff_balances
    FOR EACH ROW EXECUTE FUNCTION timeoff.timeoff_balances_audit_timestamp();

-- ==============================================================================
-- Table: TimeoffRequest (timeoff.timeoff_requests)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION timeoff.timeoff_requests_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS timeoff_requests_insert_audit ON timeoff.timeoff_requests;
CREATE TRIGGER timeoff_requests_insert_audit BEFORE INSERT ON timeoff.timeoff_requests
    FOR EACH ROW EXECUTE FUNCTION timeoff.timeoff_requests_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS timeoff_requests_update_audit ON timeoff.timeoff_requests;
CREATE TRIGGER timeoff_requests_update_audit BEFORE UPDATE ON timeoff.timeoff_requests
    FOR EACH ROW EXECUTE FUNCTION timeoff.timeoff_requests_audit_timestamp();

-- ==============================================================================
-- Table: TimeoffType (timeoff.timeoff_types)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION timeoff.timeoff_types_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS timeoff_types_insert_audit ON timeoff.timeoff_types;
CREATE TRIGGER timeoff_types_insert_audit BEFORE INSERT ON timeoff.timeoff_types
    FOR EACH ROW EXECUTE FUNCTION timeoff.timeoff_types_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS timeoff_types_update_audit ON timeoff.timeoff_types;
CREATE TRIGGER timeoff_types_update_audit BEFORE UPDATE ON timeoff.timeoff_types
    FOR EACH ROW EXECUTE FUNCTION timeoff.timeoff_types_audit_timestamp();

