//! Event handler trait for TimeoffType events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::TimeoffTypeEvent;

/// Event handler for TimeoffType events.
/// Implement this trait to react to TimeoffType lifecycle events.
pub trait TimeoffTypeEventHandler: EventHandler<TimeoffTypeEvent> {}
