//! Domain events for TimeoffBalance entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::TimeoffBalance;

/// Domain events for TimeoffBalance — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<TimeoffBalance>)` variant.
pub type TimeoffBalanceEvent = CrudEvent<TimeoffBalance>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for TimeoffBalance events.
pub type TimeoffBalanceEventPublisher = Arc<dyn CrudEventPublisher<TimeoffBalance> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopTimeoffBalanceEventPublisher = NoOpCrudEventPublisher<TimeoffBalance>;
