//! Event handler trait for TimeoffRequest events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::TimeoffRequestEvent;

/// Event handler for TimeoffRequest events.
/// Implement this trait to react to TimeoffRequest lifecycle events.
pub trait TimeoffRequestEventHandler: EventHandler<TimeoffRequestEvent> {}
