//! Domain events for TimeoffAccrualLevel entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::TimeoffAccrualLevel;

/// Domain events for TimeoffAccrualLevel — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<TimeoffAccrualLevel>)` variant.
pub type TimeoffAccrualLevelEvent = CrudEvent<TimeoffAccrualLevel>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for TimeoffAccrualLevel events.
pub type TimeoffAccrualLevelEventPublisher = Arc<dyn CrudEventPublisher<TimeoffAccrualLevel> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopTimeoffAccrualLevelEventPublisher = NoOpCrudEventPublisher<TimeoffAccrualLevel>;
