//! Event handler trait for TimeoffBalance events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::TimeoffBalanceEvent;

/// Event handler for TimeoffBalance events.
/// Implement this trait to react to TimeoffBalance lifecycle events.
pub trait TimeoffBalanceEventHandler: EventHandler<TimeoffBalanceEvent> {}
