//! Event handler trait for TimeoffAccrualLevel events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::TimeoffAccrualLevelEvent;

/// Event handler for TimeoffAccrualLevel events.
/// Implement this trait to react to TimeoffAccrualLevel lifecycle events.
pub trait TimeoffAccrualLevelEventHandler: EventHandler<TimeoffAccrualLevelEvent> {}
