//! Domain events for TimeoffType entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::TimeoffType;

/// Domain events for TimeoffType — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<TimeoffType>)` variant.
pub type TimeoffTypeEvent = CrudEvent<TimeoffType>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for TimeoffType events.
pub type TimeoffTypeEventPublisher = Arc<dyn CrudEventPublisher<TimeoffType> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopTimeoffTypeEventPublisher = NoOpCrudEventPublisher<TimeoffType>;
