//! Domain events for TimeoffRequest entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::TimeoffRequest;

/// Domain events for TimeoffRequest — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<TimeoffRequest>)` variant.
pub type TimeoffRequestEvent = CrudEvent<TimeoffRequest>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for TimeoffRequest events.
pub type TimeoffRequestEventPublisher = Arc<dyn CrudEventPublisher<TimeoffRequest> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopTimeoffRequestEventPublisher = NoOpCrudEventPublisher<TimeoffRequest>;
