//! Domain events for TimeoffAccrualPlan entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::TimeoffAccrualPlan;

/// Domain events for TimeoffAccrualPlan — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<TimeoffAccrualPlan>)` variant.
pub type TimeoffAccrualPlanEvent = CrudEvent<TimeoffAccrualPlan>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for TimeoffAccrualPlan events.
pub type TimeoffAccrualPlanEventPublisher = Arc<dyn CrudEventPublisher<TimeoffAccrualPlan> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopTimeoffAccrualPlanEventPublisher = NoOpCrudEventPublisher<TimeoffAccrualPlan>;
