//! Event handler trait for TimeoffAccrualPlan events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::TimeoffAccrualPlanEvent;

/// Event handler for TimeoffAccrualPlan events.
/// Implement this trait to react to TimeoffAccrualPlan lifecycle events.
pub trait TimeoffAccrualPlanEventHandler: EventHandler<TimeoffAccrualPlanEvent> {}
