//! TimeoffAccrualPlan seeder
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Seeds initial TimeoffAccrualPlan data into the database.

use anyhow::Result;
use async_trait::async_trait;
use sqlx::PgPool;

use super::Seeder;

// ============================================================================
// TIMEOFFACCRUALPLAN SEEDER
// ============================================================================

/// Seeder for timeoff_accrual_plan
pub struct SeedTimeoffAccrualPlanSeeder;

impl SeedTimeoffAccrualPlanSeeder {
    pub fn new() -> Self {
        Self
    }
}

impl Default for SeedTimeoffAccrualPlanSeeder {
    fn default() -> Self {
        Self::new()
    }
}

#[async_trait]
impl Seeder for SeedTimeoffAccrualPlanSeeder {
    fn name(&self) -> &'static str {
        "SeedTimeoffAccrualPlanSeeder"
    }

    fn order(&self) -> i32 {
        1
    }

    async fn should_run(&self, pool: &PgPool) -> Result<bool> {
        // Check if timeoff.timeoff_accrual_plans table has any data
        let count: (i64,) = sqlx::query_as("SELECT COUNT(*) FROM timeoff.timeoff_accrual_plans")
            .fetch_one(pool)
            .await?;
        Ok(count.0 == 0)
    }

    async fn run(&self, pool: &PgPool) -> Result<()> {
        // Run the SQL seed file
        let sql = include_str!("../../migrations/seeds/timeoff_accrual_plan_seed.sql");
        sqlx::raw_sql(sql).execute(pool).await?;
        Ok(())
    }

    async fn rollback(&self, pool: &PgPool) -> Result<()> {
        sqlx::query("DELETE FROM timeoff.timeoff_accrual_plans")
            .execute(pool)
            .await?;
        Ok(())
    }
}

// ============================================================================
// CUSTOM SEED DATA
// ============================================================================

// <<< CUSTOM SEED DATA START >>>
// Add custom seed data methods here
// <<< CUSTOM SEED DATA END >>>

