//! Repository traits
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DDD Repository traits - define persistence contracts for aggregates.
//! Implementations should be in the infrastructure layer.


pub mod timeoff_balance_repository;
pub mod timeoff_request_repository;
pub mod timeoff_type_repository;

// Re-exports
pub use timeoff_balance_repository::{
    TimeoffBalanceRepository,
    TimeoffBalancePaginationParams,
    TimeoffBalancePaginatedResult,
    TimeoffBalanceFilter,
};
pub use timeoff_request_repository::{
    TimeoffRequestRepository,
    TimeoffRequestPaginationParams,
    TimeoffRequestPaginatedResult,
    TimeoffRequestFilter,
};
pub use timeoff_type_repository::{
    TimeoffTypeRepository,
    TimeoffTypePaginationParams,
    TimeoffTypePaginatedResult,
    TimeoffTypeFilter,
};
