//! Repository trait for TimeoffAccrualPlan aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the TimeoffAccrualPlan aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::TimeoffAccrualPlan;

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct TimeoffAccrualPlanPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl TimeoffAccrualPlanPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct TimeoffAccrualPlanPaginatedResult {
    pub data: Vec<TimeoffAccrualPlan>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct TimeoffAccrualPlanFilter {
    pub company_id: Option<Uuid>,
    pub timeoff_type_id: Option<Uuid>,
    pub name: Option<String>,
}

impl TimeoffAccrualPlanFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.company_id.is_some() || self.timeoff_type_id.is_some() || self.name.is_some()
    }
}

/// Repository trait for TimeoffAccrualPlan aggregate
///
/// This trait defines the persistence contract for TimeoffAccrualPlan entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait TimeoffAccrualPlanRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new timeoff_accrual_plan entity
    async fn save(&self, entity: &TimeoffAccrualPlan) -> Result<TimeoffAccrualPlan>;

    /// Find timeoff_accrual_plan by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<TimeoffAccrualPlan>>;

    /// Find all timeoff_accrual_plan entities
    async fn find_all(&self) -> Result<Vec<TimeoffAccrualPlan>>;

    /// Update timeoff_accrual_plan by ID
    async fn update(&self, id: &str, entity: &TimeoffAccrualPlan) -> Result<Option<TimeoffAccrualPlan>>;

    /// Delete timeoff_accrual_plan by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List timeoff_accrual_plan with pagination
    async fn list(&self, params: TimeoffAccrualPlanPaginationParams) -> Result<TimeoffAccrualPlanPaginatedResult>;

    /// List timeoff_accrual_plan with pagination and filters
    async fn list_with_filters(&self, params: TimeoffAccrualPlanPaginationParams, filters: TimeoffAccrualPlanFilter) -> Result<TimeoffAccrualPlanPaginatedResult>;

    /// Count all timeoff_accrual_plan entities
    async fn count(&self) -> Result<u64>;

    /// Count timeoff_accrual_plan entities matching filters
    async fn count_with_filters(&self, filters: TimeoffAccrualPlanFilter) -> Result<u64>;

    /// Check if timeoff_accrual_plan exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete timeoff_accrual_plan by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted timeoff_accrual_plan by ID
    async fn restore(&self, id: &str) -> Result<Option<TimeoffAccrualPlan>>;

    /// List soft-deleted timeoff_accrual_plan entities
    async fn list_deleted(&self, params: TimeoffAccrualPlanPaginationParams) -> Result<TimeoffAccrualPlanPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save timeoff_accrual_plan entities
    async fn bulk_save(&self, entities: &[TimeoffAccrualPlan]) -> Result<Vec<TimeoffAccrualPlan>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
