//! Repository trait for TimeoffBalance aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the TimeoffBalance aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::TimeoffBalance;

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct TimeoffBalancePaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl TimeoffBalancePaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct TimeoffBalancePaginatedResult {
    pub data: Vec<TimeoffBalance>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct TimeoffBalanceFilter {
    pub timeoff_type_id: Option<Uuid>,
    pub employee_id: Option<Uuid>,
    pub period: Option<String>,
    pub accrual_plan_id: Option<Uuid>,
}

impl TimeoffBalanceFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.timeoff_type_id.is_some() || self.employee_id.is_some() || self.period.is_some() || self.accrual_plan_id.is_some()
    }
}

/// Repository trait for TimeoffBalance aggregate
///
/// This trait defines the persistence contract for TimeoffBalance entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait TimeoffBalanceRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new timeoff_balance entity
    async fn save(&self, entity: &TimeoffBalance) -> Result<TimeoffBalance>;

    /// Find timeoff_balance by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<TimeoffBalance>>;

    /// Find all timeoff_balance entities
    async fn find_all(&self) -> Result<Vec<TimeoffBalance>>;

    /// Update timeoff_balance by ID
    async fn update(&self, id: &str, entity: &TimeoffBalance) -> Result<Option<TimeoffBalance>>;

    /// Delete timeoff_balance by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List timeoff_balance with pagination
    async fn list(&self, params: TimeoffBalancePaginationParams) -> Result<TimeoffBalancePaginatedResult>;

    /// List timeoff_balance with pagination and filters
    async fn list_with_filters(&self, params: TimeoffBalancePaginationParams, filters: TimeoffBalanceFilter) -> Result<TimeoffBalancePaginatedResult>;

    /// Count all timeoff_balance entities
    async fn count(&self) -> Result<u64>;

    /// Count timeoff_balance entities matching filters
    async fn count_with_filters(&self, filters: TimeoffBalanceFilter) -> Result<u64>;

    /// Check if timeoff_balance exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete timeoff_balance by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted timeoff_balance by ID
    async fn restore(&self, id: &str) -> Result<Option<TimeoffBalance>>;

    /// List soft-deleted timeoff_balance entities
    async fn list_deleted(&self, params: TimeoffBalancePaginationParams) -> Result<TimeoffBalancePaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save timeoff_balance entities
    async fn bulk_save(&self, entities: &[TimeoffBalance]) -> Result<Vec<TimeoffBalance>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
