//! Repository trait for TimeoffRequest aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the TimeoffRequest aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::{TimeoffRequest, TimeoffRequestStatus};

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct TimeoffRequestPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl TimeoffRequestPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct TimeoffRequestPaginatedResult {
    pub data: Vec<TimeoffRequest>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct TimeoffRequestFilter {
    pub company_id: Option<Uuid>,
    pub timeoff_type_id: Option<Uuid>,
    pub employee_id: Option<Uuid>,
    pub note: Option<String>,
    pub approval_employee_id: Option<Uuid>,
    pub note_reject: Option<String>,
    pub status: Option<TimeoffRequestStatus>,
}

impl TimeoffRequestFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.company_id.is_some() || self.timeoff_type_id.is_some() || self.employee_id.is_some() || self.note.is_some() || self.approval_employee_id.is_some() || self.note_reject.is_some() || self.status.is_some()
    }
}

/// Repository trait for TimeoffRequest aggregate
///
/// This trait defines the persistence contract for TimeoffRequest entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait TimeoffRequestRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new timeoff_request entity
    async fn save(&self, entity: &TimeoffRequest) -> Result<TimeoffRequest>;

    /// Find timeoff_request by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<TimeoffRequest>>;

    /// Find all timeoff_request entities
    async fn find_all(&self) -> Result<Vec<TimeoffRequest>>;

    /// Update timeoff_request by ID
    async fn update(&self, id: &str, entity: &TimeoffRequest) -> Result<Option<TimeoffRequest>>;

    /// Delete timeoff_request by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List timeoff_request with pagination
    async fn list(&self, params: TimeoffRequestPaginationParams) -> Result<TimeoffRequestPaginatedResult>;

    /// List timeoff_request with pagination and filters
    async fn list_with_filters(&self, params: TimeoffRequestPaginationParams, filters: TimeoffRequestFilter) -> Result<TimeoffRequestPaginatedResult>;

    /// Count all timeoff_request entities
    async fn count(&self) -> Result<u64>;

    /// Count timeoff_request entities matching filters
    async fn count_with_filters(&self, filters: TimeoffRequestFilter) -> Result<u64>;

    /// Check if timeoff_request exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete timeoff_request by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted timeoff_request by ID
    async fn restore(&self, id: &str) -> Result<Option<TimeoffRequest>>;

    /// List soft-deleted timeoff_request entities
    async fn list_deleted(&self, params: TimeoffRequestPaginationParams) -> Result<TimeoffRequestPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save timeoff_request entities
    async fn bulk_save(&self, entities: &[TimeoffRequest]) -> Result<Vec<TimeoffRequest>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
