//! Repository trait for TimeoffAccrualLevel aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the TimeoffAccrualLevel aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::{TimeoffAccrualLevel, AccrualFrequency, AccrualLostDaysAction, AccrualStartType};

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct TimeoffAccrualLevelPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl TimeoffAccrualLevelPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct TimeoffAccrualLevelPaginatedResult {
    pub data: Vec<TimeoffAccrualLevel>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct TimeoffAccrualLevelFilter {
    pub company_id: Option<Uuid>,
    pub plan_id: Option<Uuid>,
    pub start_type: Option<AccrualStartType>,
    pub frequency: Option<AccrualFrequency>,
    pub is_added_based_on_worked_time: Option<bool>,
    pub action_with_lost_days: Option<AccrualLostDaysAction>,
}

impl TimeoffAccrualLevelFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.company_id.is_some() || self.plan_id.is_some() || self.start_type.is_some() || self.frequency.is_some() || self.is_added_based_on_worked_time.is_some() || self.action_with_lost_days.is_some()
    }
}

/// Repository trait for TimeoffAccrualLevel aggregate
///
/// This trait defines the persistence contract for TimeoffAccrualLevel entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait TimeoffAccrualLevelRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new timeoff_accrual_level entity
    async fn save(&self, entity: &TimeoffAccrualLevel) -> Result<TimeoffAccrualLevel>;

    /// Find timeoff_accrual_level by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<TimeoffAccrualLevel>>;

    /// Find all timeoff_accrual_level entities
    async fn find_all(&self) -> Result<Vec<TimeoffAccrualLevel>>;

    /// Update timeoff_accrual_level by ID
    async fn update(&self, id: &str, entity: &TimeoffAccrualLevel) -> Result<Option<TimeoffAccrualLevel>>;

    /// Delete timeoff_accrual_level by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List timeoff_accrual_level with pagination
    async fn list(&self, params: TimeoffAccrualLevelPaginationParams) -> Result<TimeoffAccrualLevelPaginatedResult>;

    /// List timeoff_accrual_level with pagination and filters
    async fn list_with_filters(&self, params: TimeoffAccrualLevelPaginationParams, filters: TimeoffAccrualLevelFilter) -> Result<TimeoffAccrualLevelPaginatedResult>;

    /// Count all timeoff_accrual_level entities
    async fn count(&self) -> Result<u64>;

    /// Count timeoff_accrual_level entities matching filters
    async fn count_with_filters(&self, filters: TimeoffAccrualLevelFilter) -> Result<u64>;

    /// Check if timeoff_accrual_level exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete timeoff_accrual_level by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted timeoff_accrual_level by ID
    async fn restore(&self, id: &str) -> Result<Option<TimeoffAccrualLevel>>;

    /// List soft-deleted timeoff_accrual_level entities
    async fn list_deleted(&self, params: TimeoffAccrualLevelPaginationParams) -> Result<TimeoffAccrualLevelPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save timeoff_accrual_level entities
    async fn bulk_save(&self, entities: &[TimeoffAccrualLevel]) -> Result<Vec<TimeoffAccrualLevel>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
