//! Repository trait for TimeoffType aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the TimeoffType aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::TimeoffType;

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct TimeoffTypePaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl TimeoffTypePaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct TimeoffTypePaginatedResult {
    pub data: Vec<TimeoffType>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct TimeoffTypeFilter {
    pub company_id: Option<Uuid>,
    pub name: Option<String>,
    pub code: Option<String>,
    pub is_paid: Option<bool>,
    pub allow_carry_forward: Option<bool>,
}

impl TimeoffTypeFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.company_id.is_some() || self.name.is_some() || self.code.is_some() || self.is_paid.is_some() || self.allow_carry_forward.is_some()
    }
}

/// Repository trait for TimeoffType aggregate
///
/// This trait defines the persistence contract for TimeoffType entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait TimeoffTypeRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new timeoff_type entity
    async fn save(&self, entity: &TimeoffType) -> Result<TimeoffType>;

    /// Find timeoff_type by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<TimeoffType>>;

    /// Find all timeoff_type entities
    async fn find_all(&self) -> Result<Vec<TimeoffType>>;

    /// Update timeoff_type by ID
    async fn update(&self, id: &str, entity: &TimeoffType) -> Result<Option<TimeoffType>>;

    /// Delete timeoff_type by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List timeoff_type with pagination
    async fn list(&self, params: TimeoffTypePaginationParams) -> Result<TimeoffTypePaginatedResult>;

    /// List timeoff_type with pagination and filters
    async fn list_with_filters(&self, params: TimeoffTypePaginationParams, filters: TimeoffTypeFilter) -> Result<TimeoffTypePaginatedResult>;

    /// Count all timeoff_type entities
    async fn count(&self) -> Result<u64>;

    /// Count timeoff_type entities matching filters
    async fn count_with_filters(&self, filters: TimeoffTypeFilter) -> Result<u64>;

    /// Check if timeoff_type exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete timeoff_type by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted timeoff_type by ID
    async fn restore(&self, id: &str) -> Result<Option<TimeoffType>>;

    /// List soft-deleted timeoff_type entities
    async fn list_deleted(&self, params: TimeoffTypePaginationParams) -> Result<TimeoffTypePaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save timeoff_type entities
    async fn bulk_save(&self, entities: &[TimeoffType]) -> Result<Vec<TimeoffType>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
