//! Repository implementations
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Uses backbone-orm's `DatabaseOperations<T>` trait.

mod timeoff_accrual_plan_repository;
mod timeoff_accrual_level_repository;
mod timeoff_balance_repository;
mod timeoff_request_repository;
mod timeoff_type_repository;

// Custom persistence modules
// <<< CUSTOM
// The accrual walk's SQL (Wave 1 P1, H-2): SKIP LOCKED claim, plan-ladder read,
// optimistic-guarded grant apply, expiry stamp. User-owned — see
// metaphor.codegen.yaml.
mod timeoff_accrual_repository;
// END CUSTOM

// Re-exports
pub use timeoff_accrual_plan_repository::TimeoffAccrualPlanRepository;
pub use timeoff_accrual_level_repository::TimeoffAccrualLevelRepository;
pub use timeoff_balance_repository::TimeoffBalanceRepository;
pub use timeoff_request_repository::TimeoffRequestRepository;
pub use timeoff_type_repository::TimeoffTypeRepository;

// Re-export backbone-orm types
pub use backbone_orm::repository::{
    DatabaseOperations, PostgresRepository,
    PaginationParams, PaginationInfo, PaginatedResult,
    FilterParams, FilterCondition, SortParams, SortDirection,
};

// Re-export custom persistence types
// <<< CUSTOM
pub use timeoff_accrual_repository::{
    AccrualLevelRow, AccrualWalkRow, TimeoffAccrualRepository,
};
// The submit verb's draft (client-generated id + optional approvals link).
pub use timeoff_request_repository::TimeoffRequestDraft;
// END CUSTOM
