//! Repository for TimeoffRequest entities
//!
//! Originally generated by metaphor-schema; now **user-owned** — this exact path is declared under
//! `user_owned` in `metaphor.codegen.yaml`, so the generator skips it wholesale. The custom methods
//! below hold the hand-written TimeoffRequest SQL — both the `paid_leave_days` read-port and the
//! approve/reject/cancel transitions that pair with `TimeoffBalanceRepository`'s draw/restore to form
//! the leave-drawdown invariant (4-layer rule: services orchestrate, repos hold SQL).
//!
//! Ported verbatim from backbone-hr's `leave_application_repository.rs`. The schema-driven
//! adaptations: `timeoff_requests` has no `days` column, so `days` is computed in the SELECT as the
//! inclusive span `(date_end - date_start + 1)`; the approver column is `approval_employee_id`
//! (there is no `approved_at`); balances are keyed on `period` (TEXT) not `year` (see the balance
//! repo). The tx + gating contract is identical to backbone-hr.
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<TimeoffRequest, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use chrono::NaiveDate;
use rust_decimal::Decimal;
use sqlx::{PgPool, Row};
use uuid::Uuid;

use backbone_orm::company_scope;

use crate::domain::entity::TimeoffRequest;

/// Table name for TimeoffRequest entities
pub const TABLE_NAME: &str = "timeoff.timeoff_requests";

/// Repository for TimeoffRequest entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct TimeoffRequestRepository(
    backbone_orm::GenericCrudRepository<TimeoffRequest, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for TimeoffRequestRepository {
    type Target = backbone_orm::GenericCrudRepository<TimeoffRequest, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl TimeoffRequestRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

/// What the approval path reads before it draws: the request joined to its type, carrying the
/// company that binds the transaction and the `is_paid` polarity the (future) event announces.
/// Mirrors backbone-hr's `LeaveApprovalRow`; `days` is computed here, not read off a stored column.
pub struct TimeoffApprovalRow {
    pub company_id: Uuid,
    pub employee_id: Uuid,
    pub timeoff_type_id: Uuid,
    pub days: Decimal,
    pub date_start: NaiveDate,
    pub date_end: NaiveDate,
    pub status: String,
    pub is_paid: bool,
    /// The approvals seam link (Wave 1 P1): set when the request was filed with
    /// a wired `ApprovalFiling` port — `approve_request` then requires the
    /// linked ApprovalRequest to be approved (TR2).
    pub approval_request_id: Option<Uuid>,
}

/// What the cancellation path reads before it restores. Mirrors backbone-hr's `LeaveCancelRow`;
/// carries both window ends so the settled event can echo the full span.
pub struct TimeoffCancelRow {
    pub company_id: Uuid,
    pub employee_id: Uuid,
    pub timeoff_type_id: Uuid,
    pub days: Decimal,
    pub date_start: NaiveDate,
    pub date_end: NaiveDate,
    pub status: String,
}

/// What the reject path's RETURNING hands back: the settle-relevant fields for the domain event.
pub struct TimeoffRejectedRow {
    pub company_id: Uuid,
    pub employee_id: Uuid,
    pub date_start: NaiveDate,
    pub date_end: NaiveDate,
}

/// A new request as the submit verb builds it (Wave 1 P1). `id` is
/// client-generated so the approvals filing can carry it as the correlation id
/// BEFORE the row exists (file-first ordering — see
/// `TimeoffRequestWriteService::submit_request`).
pub struct TimeoffRequestDraft {
    pub id: Uuid,
    pub company_id: Uuid,
    pub timeoff_type_id: Uuid,
    pub employee_id: Uuid,
    pub date_start: NaiveDate,
    pub date_end: NaiveDate,
    pub note: Option<String>,
    /// Set when a wired `ApprovalFiling` port already filed the approval.
    pub approval_request_id: Option<Uuid>,
}

/// Hand-written TimeoffRequest SQL — both the read-port and the approve/reject/cancel transitions.
/// Lives here (not in the write service) per the module's 4-layer rule: services orchestrate and own
/// the unit of work, repositories hold the SQL.
impl TimeoffRequestRepository {
    /// The dates in `[from, to]` (inclusive) covered by an **approved** `TimeoffRequest` whose
    /// `TimeoffType.is_paid = true` — i.e. paid leave days, what payroll subtracts from working days.
    ///
    /// Each request's `[date_start, date_end]` is clamped to `[from, to]` and expanded into individual
    /// days in SQL via `generate_series` (single round trip; no Rust-side date iteration). `DISTINCT`
    /// collapses overlaps so a day covered by two paid requests is counted once.
    ///
    /// Read-only, company-scoped: takes the pool and runs `fetch_all_scoped` so the RLS fence
    /// (ADR-0008) applies. The caller wraps this in `with_company_scope(Some(company_id))` (or the
    /// HTTP composition root's `with_request_scope`) — otherwise it fails closed (0 rows).
    ///
    /// Soft-delete lives in the request's `metadata` JSONB column (`deleted_at` key); the
    /// `(metadata->>'deleted_at') IS NULL` predicate mirrors every other non-deleted read. The joined
    /// `timeoff_types` row is NOT soft-delete-filtered — `is_paid` is meaningful regardless of the
    /// type's lifecycle, matching the backbone-hr `sum_approved_days_by_paid` reference.
    pub async fn paid_leave_days(
        &self,
        pool: &PgPool,
        company_id: Uuid,
        employee_id: Uuid,
        from: NaiveDate,
        to: NaiveDate,
    ) -> Result<Vec<NaiveDate>, sqlx::Error> {
        // No `fetch_all_scalar_scoped` exists in backbone_orm, so decode the single DATE column as a
        // 1-tuple row via `fetch_all_scoped` and unwrap the tuple — the documented shape for a
        // single-column typed read (mirrors `AttendanceRepository::present_days`).
        let rows: Vec<(NaiveDate,)> = company_scope::fetch_all_scoped(
            pool,
            sqlx::query_as(
                r#"SELECT DISTINCT d.day::date AS day
                   FROM timeoff.timeoff_requests tr
                   JOIN timeoff.timeoff_types tt ON tt.id = tr.timeoff_type_id
                   CROSS JOIN LATERAL generate_series(
                       GREATEST(tr.date_start, $3)::timestamp,
                       LEAST(tr.date_end, $4)::timestamp,
                       '1 day'::interval
                   ) AS d(day)
                   WHERE tr.company_id = $1
                     AND tr.employee_id = $2
                     AND tr.status = 'approved'::timeoff_request_status
                     AND tt.is_paid = true
                     AND tr.date_start <= $4
                     AND tr.date_end >= $3
                     AND (tr.metadata->>'deleted_at') IS NULL
                   ORDER BY day"#,
            )
            .bind(company_id)
            .bind(employee_id)
            .bind(from)
            .bind(to),
        )
        .await?;
        Ok(rows.into_iter().map(|(d,)| d).collect())
    }

    /// Read a request + its type for approval. `Ok(None)` = no such live request in scope.
    ///
    /// ID-only: no company argument. `fetch_optional_row_scoped` means it rides a connection carrying
    /// the caller's `app.company_id`, so another company's request simply is not found. The company
    /// comes back on the row precisely so the caller can bind the approval transaction to it explicitly
    /// — which is what fences the transition + draw even for non-request callers.
    ///
    /// `days` is computed in SQL as the inclusive span `(date_end - date_start + 1)` because
    /// `timeoff_requests` has no stored `days` column (unlike backbone-hr's `leave_applications`).
    /// The join to `timeoff_types` carries `is_paid` for the (future) `RequestApproved` event, exactly
    /// as backbone-hr's `find_for_approval` does.
    pub async fn find_for_approval(
        &self,
        pool: &PgPool,
        timeoff_request_id: Uuid,
    ) -> Result<Option<TimeoffApprovalRow>, sqlx::Error> {
        let row = company_scope::fetch_optional_row_scoped(
            pool,
            sqlx::query(
                r#"SELECT tr.company_id, tr.employee_id, tr.timeoff_type_id,
                          (tr.date_end - tr.date_start + 1)::numeric AS days,
                          tr.date_start, tr.date_end, tr.status::text AS status, tt.is_paid,
                          tr.approval_request_id
                   FROM timeoff.timeoff_requests tr
                   JOIN timeoff.timeoff_types tt ON tt.id = tr.timeoff_type_id
                   WHERE tr.id=$1 AND (tr.metadata->>'deleted_at') IS NULL"#,
            )
            .bind(timeoff_request_id),
        )
        .await?;
        Ok(row.map(|r| TimeoffApprovalRow {
            company_id: r.get("company_id"), employee_id: r.get("employee_id"),
            timeoff_type_id: r.get("timeoff_type_id"), days: r.get("days"),
            date_start: r.get("date_start"), date_end: r.get("date_end"),
            status: r.get("status"), is_paid: r.get("is_paid"),
            approval_request_id: r.get("approval_request_id"),
        }))
    }

    /// Claim the `pending → approved` transition (write-once). Returns rows affected: 0 = someone else
    /// already moved it and the caller must roll back.
    ///
    /// Takes the CALLER'S connection so this and the balance draw commit as ONE unit — the module's
    /// load-bearing invariant. The caller has already bound the company on it — don't re-bind here.
    /// Sets `approval_employee_id` (the timeoff schema has no `approved_at`; the audit `updated_at` is
    /// stamped by the table's BEFORE UPDATE trigger).
    pub async fn mark_approved(
        &self,
        conn: &mut sqlx::PgConnection,
        timeoff_request_id: Uuid,
        approver: Option<Uuid>,
    ) -> Result<u64, sqlx::Error> {
        let done = sqlx::query(
            r#"UPDATE timeoff.timeoff_requests
               SET status='approved'::timeoff_request_status, approval_employee_id=$2
               WHERE id=$1 AND status='pending'::timeoff_request_status"#,
        )
        .bind(timeoff_request_id).bind(approver)
        .execute(conn)
        .await?;
        Ok(done.rows_affected())
    }

    /// Reject a pending request (no balance change). `Ok(None)` = not pending (or not found in
    /// scope); a row means the rejection landed and carries the settle-relevant fields for the
    /// `LeaveSettled` event.
    ///
    /// ID-only: no company argument — `fetch_optional_row_scoped` rides the request-dedicated
    /// connection, so another company's request is simply not matched.
    pub async fn mark_rejected(
        &self,
        pool: &PgPool,
        timeoff_request_id: Uuid,
    ) -> Result<Option<TimeoffRejectedRow>, sqlx::Error> {
        let row = company_scope::fetch_optional_row_scoped(
            pool,
            sqlx::query(
                r#"UPDATE timeoff.timeoff_requests SET status='rejected'::timeoff_request_status
                   WHERE id=$1 AND status='pending'::timeoff_request_status
                     AND (metadata->>'deleted_at') IS NULL
                   RETURNING company_id, employee_id, date_start, date_end"#,
            )
            .bind(timeoff_request_id),
        )
        .await?;
        Ok(row.map(|r| TimeoffRejectedRow {
            company_id: r.get("company_id"),
            employee_id: r.get("employee_id"),
            date_start: r.get("date_start"),
            date_end: r.get("date_end"),
        }))
    }

    /// Read a request for cancellation. `Ok(None)` = no such live request in scope.
    ///
    /// ID-only, fenced as [`Self::find_for_approval`]. The projection carries `company_id` deliberately:
    /// the restore transaction below binds it explicitly, which is what makes the invariant-critical
    /// path correct for non-request callers too.
    pub async fn find_for_cancel(
        &self,
        pool: &PgPool,
        timeoff_request_id: Uuid,
    ) -> Result<Option<TimeoffCancelRow>, sqlx::Error> {
        let row = company_scope::fetch_optional_row_scoped(
            pool,
            sqlx::query(
                r#"SELECT company_id, employee_id, timeoff_type_id,
                          (date_end - date_start + 1)::numeric AS days,
                          date_start, date_end, status::text AS status
                   FROM timeoff.timeoff_requests
                   WHERE id=$1 AND (metadata->>'deleted_at') IS NULL"#,
            )
            .bind(timeoff_request_id),
        )
        .await?;
        Ok(row.map(|r| TimeoffCancelRow {
            company_id: r.get("company_id"), employee_id: r.get("employee_id"),
            timeoff_type_id: r.get("timeoff_type_id"), days: r.get("days"),
            date_start: r.get("date_start"), date_end: r.get("date_end"),
            status: r.get("status"),
        }))
    }

    /// Cancel a PENDING request — nothing was drawn, so there is no balance to restore and no
    /// transaction to own. Returns rows affected: 0 = not cancellable. ID-only, as above.
    pub async fn cancel_pending(
        &self,
        pool: &PgPool,
        timeoff_request_id: Uuid,
    ) -> Result<u64, sqlx::Error> {
        let done = company_scope::execute_scoped(
            pool,
            sqlx::query(
                "UPDATE timeoff.timeoff_requests SET status='cancelled'::timeoff_request_status \
                 WHERE id=$1 AND status='pending'::timeoff_request_status")
                .bind(timeoff_request_id),
        )
        .await?;
        Ok(done.rows_affected())
    }

    /// Cancel an APPROVED request. Returns rows affected: 0 = not approved, caller must roll back.
    ///
    /// Takes the CALLER'S connection so this and the balance restore commit as ONE unit (a balance is
    /// never left short). The caller has already bound the company on it — don't re-bind here.
    pub async fn cancel_approved(
        &self,
        conn: &mut sqlx::PgConnection,
        timeoff_request_id: Uuid,
    ) -> Result<u64, sqlx::Error> {
        let done = sqlx::query(
            r#"UPDATE timeoff.timeoff_requests SET status='cancelled'::timeoff_request_status
               WHERE id=$1 AND status='approved'::timeoff_request_status"#,
        )
        .bind(timeoff_request_id)
        .execute(conn)
        .await?;
        Ok(done.rows_affected())
    }

    /// Insert a fresh `pending` request. Takes the CALLER'S connection (the
    /// company is bound on it). Returns rows affected: 0 = rejected by a
    /// constraint (e.g. the type does not exist).
    pub async fn insert_pending(
        &self,
        conn: &mut sqlx::PgConnection,
        d: &TimeoffRequestDraft,
    ) -> Result<u64, sqlx::Error> {
        let done = sqlx::query(
            r#"INSERT INTO timeoff.timeoff_requests
                   (id, company_id, timeoff_type_id, employee_id,
                    date_start, date_end, note, approval_request_id, status)
               VALUES ($1, $2, $3, $4, $5, $6, $7, $8, 'pending'::timeoff_request_status)"#,
        )
        .bind(d.id)
        .bind(d.company_id)
        .bind(d.timeoff_type_id)
        .bind(d.employee_id)
        .bind(d.date_start)
        .bind(d.date_end)
        .bind(&d.note)
        .bind(d.approval_request_id)
        .execute(conn)
        .await?;
        Ok(done.rows_affected())
    }
}

backbone_core::impl_crud_repository!(TimeoffRequestRepository, TimeoffRequest, soft_delete);
