//! Repository for TimeoffAccrualLevel entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<TimeoffAccrualLevel, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;

use crate::domain::entity::TimeoffAccrualLevel;

/// Table name for TimeoffAccrualLevel entities
pub const TABLE_NAME: &str = "timeoff.timeoff_accrual_levels";

/// Repository for TimeoffAccrualLevel entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct TimeoffAccrualLevelRepository(
    backbone_orm::GenericCrudRepository<TimeoffAccrualLevel, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for TimeoffAccrualLevelRepository {
    type Target = backbone_orm::GenericCrudRepository<TimeoffAccrualLevel, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl TimeoffAccrualLevelRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

backbone_core::impl_crud_repository!(TimeoffAccrualLevelRepository, TimeoffAccrualLevel, soft_delete);
