//! Repository for TimeoffAccrualPlan entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<TimeoffAccrualPlan, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;

use crate::domain::entity::TimeoffAccrualPlan;

/// Table name for TimeoffAccrualPlan entities
pub const TABLE_NAME: &str = "timeoff.timeoff_accrual_plans";

/// Repository for TimeoffAccrualPlan entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct TimeoffAccrualPlanRepository(
    backbone_orm::GenericCrudRepository<TimeoffAccrualPlan, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for TimeoffAccrualPlanRepository {
    type Target = backbone_orm::GenericCrudRepository<TimeoffAccrualPlan, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl TimeoffAccrualPlanRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

backbone_core::impl_crud_repository!(TimeoffAccrualPlanRepository, TimeoffAccrualPlan, soft_delete);
