//! Repository for TimeoffBalance entities
//!
//! Originally generated by metaphor-schema; now **user-owned** — this exact path is declared under
//! `user_owned` in `metaphor.codegen.yaml`, so the generator skips it wholesale. The custom methods
//! below hold the hand-written TimeoffBalance SQL — the module's load-bearing invariant (4-layer
//! rule: services orchestrate and own the unit of work, repositories hold the SQL).
//!
//! Ported verbatim from backbone-hr's `leave_balance_repository.rs`. The one schema-driven
//! adaptation: backbone-hr keys a balance on `year` (INTEGER); timeoff keys it on `period` (TEXT,
//! e.g. "2026"). The gating logic is identical — `used + days <= allocated` on draw,
//! `used >= days` on restore — and the DB CHECK backstop (`used <= allocated`, `used >= 0`,
//! installed by the `timeoff_balance_guards` migration) makes a bug here fail closed (rejected tx),
//! never corrupt the balance.
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<TimeoffBalance, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use rust_decimal::Decimal;
use sqlx::PgPool;
use uuid::Uuid;

use crate::domain::entity::TimeoffBalance;

/// Table name for TimeoffBalance entities
pub const TABLE_NAME: &str = "timeoff.timeoff_balances";

/// Repository for TimeoffBalance entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct TimeoffBalanceRepository(
    backbone_orm::GenericCrudRepository<TimeoffBalance, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for TimeoffBalanceRepository {
    type Target = backbone_orm::GenericCrudRepository<TimeoffBalance, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl TimeoffBalanceRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

/// Hand-written TimeoffBalance SQL — the leave-balance engine. Lives here (not in the write service)
/// per the module's 4-layer rule: services orchestrate and own the unit of work, repositories hold
/// the SQL. Ported from backbone-hr's `LeaveBalanceRepository`.
impl TimeoffBalanceRepository {
    /// Draw down a balance on approval, GATED on availability AND on the accrual
    /// validity window (Wave 1 P1, H-2): the row moves only if
    /// `used + days <= allocated` and the request's `[date_start, date_end]`
    /// falls inside the balance's `[date_from, date_to]` (either bound open when
    /// NULL — a manually-granted balance has no window). Returns rows affected:
    /// 0 = insufficient (or missing or window-missed) balance, and the caller
    /// must roll back. This gate IS the invariant — you cannot approve leave you
    /// don't have or spend an allocation outside its validity.
    ///
    /// Takes the CALLER'S connection so the draw and the request's `pending → approved` transition
    /// commit as ONE unit. The caller has already relayed the ambient org scope onto it
    /// (`org_scope::bind_org_scope_on`, when one is mounted) — don't re-bind here.
    pub async fn draw(
        &self,
        conn: &mut sqlx::PgConnection,
        employee_id: Uuid,
        timeoff_type_id: Uuid,
        period: &str,
        days: Decimal,
        date_start: chrono::NaiveDate,
        date_end: chrono::NaiveDate,
    ) -> Result<u64, sqlx::Error> {
        let done = sqlx::query(
            r#"UPDATE timeoff.timeoff_balances SET used = used + $4
               WHERE employee_id=$1 AND timeoff_type_id=$2 AND period=$3 AND used + $4 <= allocated
                 AND (date_from IS NULL OR date_from <= $5)
                 AND (date_to   IS NULL OR date_to   >= $6)"#,
        )
        .bind(employee_id).bind(timeoff_type_id).bind(period).bind(days)
        .bind(date_start).bind(date_end)
        .execute(conn)
        .await?;
        Ok(done.rows_affected())
    }

    /// Restore a drawn-down balance on cancellation. Returns rows affected: 0 = the caller must roll back.
    ///
    /// GATED on `used >= days` so a tampered request (its `days` mutated after approval via the
    /// generic PATCH surface) can never drive `used` negative and manufacture phantom entitlement.
    /// The DB CHECK `used >= 0` is the backstop for any other writer; this gate turns the violation
    /// into a clean domain error instead of a raw error.
    ///
    /// Same caller-owned-tx contract as [`Self::draw`]: the restore and the transition are one unit.
    pub async fn restore(
        &self,
        conn: &mut sqlx::PgConnection,
        employee_id: Uuid,
        timeoff_type_id: Uuid,
        period: &str,
        days: Decimal,
    ) -> Result<u64, sqlx::Error> {
        let done = sqlx::query(
            r#"UPDATE timeoff.timeoff_balances SET used = used - $4
               WHERE employee_id=$1 AND timeoff_type_id=$2 AND period=$3 AND used >= $4"#,
        )
        .bind(employee_id).bind(timeoff_type_id).bind(period).bind(days)
        .execute(conn)
        .await?;
        Ok(done.rows_affected())
    }
}

backbone_core::impl_crud_repository!(TimeoffBalanceRepository, TimeoffBalance, soft_delete);
