//! Repository for TimeoffType entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<TimeoffType, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;

use crate::domain::entity::TimeoffType;

/// Table name for TimeoffType entities
pub const TABLE_NAME: &str = "timeoff.timeoff_types";

/// Repository for TimeoffType entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct TimeoffTypeRepository(
    backbone_orm::GenericCrudRepository<TimeoffType, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for TimeoffTypeRepository {
    type Target = backbone_orm::GenericCrudRepository<TimeoffType, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl TimeoffTypeRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

backbone_core::impl_crud_repository!(TimeoffTypeRepository, TimeoffType, soft_delete);
