//! Validator for TimeoffType entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<TimeoffType>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{OptionalNotBlank, RequiredString};
use crate::domain::entity::TimeoffType;

/// Validator type alias for TimeoffType entities.
pub type TimeoffTypeValidator = EntityValidator<TimeoffType>;

/// Build a validator for TimeoffType with all schema-defined field rules.
pub fn timeoff_type_validator() -> TimeoffTypeValidator {
    EntityValidator::new()
        .rule(RequiredString::new("name", |e: &TimeoffType| &e.name))
        .rule(OptionalNotBlank::new("code", |e: &TimeoffType| e.code.as_deref()))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
