//! Validator for TimeoffAccrualLevel entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<TimeoffAccrualLevel>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{NonNegative};
use crate::domain::entity::TimeoffAccrualLevel;

/// Validator type alias for TimeoffAccrualLevel entities.
pub type TimeoffAccrualLevelValidator = EntityValidator<TimeoffAccrualLevel>;

/// Build a validator for TimeoffAccrualLevel with all schema-defined field rules.
pub fn timeoff_accrual_level_validator() -> TimeoffAccrualLevelValidator {
    EntityValidator::new()
    // <<< CUSTOM RULES
    // END CUSTOM RULES
        // No schema-derived rules — add custom rules above.
}

// <<< CUSTOM
// END CUSTOM
