//! Validator for TimeoffRequest entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<TimeoffRequest>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{OptionalNotBlank};
use crate::domain::entity::TimeoffRequest;

/// Validator type alias for TimeoffRequest entities.
pub type TimeoffRequestValidator = EntityValidator<TimeoffRequest>;

/// Build a validator for TimeoffRequest with all schema-defined field rules.
pub fn timeoff_request_validator() -> TimeoffRequestValidator {
    EntityValidator::new()
        .rule(OptionalNotBlank::new("note", |e: &TimeoffRequest| e.note.as_deref()))
        .rule(OptionalNotBlank::new("note_reject", |e: &TimeoffRequest| e.note_reject.as_deref()))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
