//! Validator for TimeoffBalance entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<TimeoffBalance>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{NonNegative, RequiredString};
use crate::domain::entity::TimeoffBalance;

/// Validator type alias for TimeoffBalance entities.
pub type TimeoffBalanceValidator = EntityValidator<TimeoffBalance>;

/// Build a validator for TimeoffBalance with all schema-defined field rules.
pub fn timeoff_balance_validator() -> TimeoffBalanceValidator {
    EntityValidator::new()
        .rule(RequiredString::new("period", |e: &TimeoffBalance| &e.period))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
