//! Validator for TimeoffAccrualPlan entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<TimeoffAccrualPlan>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{RequiredString};
use crate::domain::entity::TimeoffAccrualPlan;

/// Validator type alias for TimeoffAccrualPlan entities.
pub type TimeoffAccrualPlanValidator = EntityValidator<TimeoffAccrualPlan>;

/// Build a validator for TimeoffAccrualPlan with all schema-defined field rules.
pub fn timeoff_accrual_plan_validator() -> TimeoffAccrualPlanValidator {
    EntityValidator::new()
        .rule(RequiredString::new("name", |e: &TimeoffAccrualPlan| &e.name))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
