//! Auth policies and guards
//!
//! Generated by metaphor-schema. Do not edit manually.

pub mod timeoff_balance_auth;
pub mod timeoff_request_auth;
pub mod timeoff_type_auth;

pub use timeoff_balance_auth::{TimeoffBalancePolicy, TimeoffBalanceGuard, TimeoffBalanceServiceGuard};
pub use timeoff_request_auth::{TimeoffRequestPolicy, TimeoffRequestGuard, TimeoffRequestServiceGuard};
pub use timeoff_type_auth::{TimeoffTypePolicy, TimeoffTypeGuard, TimeoffTypeServiceGuard};

// <<< CUSTOM
// END CUSTOM
