//! Auth configuration for TimeoffType handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Implements `ResourcePolicy<TimeoffType>` with entity-specific permission
//! string constants. Guard middleware logic lives in backbone-auth.

use backbone_auth::{ResourcePolicy, ResourceAction, PermissionGuard, ServicePermissionGuard};
use async_trait::async_trait;

use crate::application::service::TimeoffTypeService;
use crate::domain::entity::TimeoffType;

/// Permission string constants for TimeoffType operations.
pub mod permissions {
    pub const LIST:        &str = "timeoff_type:list";
    pub const READ:        &str = "timeoff_type:read";
    pub const CREATE:      &str = "timeoff_type:create";
    pub const UPDATE:      &str = "timeoff_type:update";
    pub const DELETE:      &str = "timeoff_type:delete";
    pub const RESTORE:     &str = "timeoff_type:restore";
    pub const TRASH:       &str = "timeoff_type:trash";
    pub const EMPTY_TRASH: &str = "timeoff_type:empty_trash";
    pub const BULK_CREATE: &str = "timeoff_type:bulk_create";
    pub const UPSERT:      &str = "timeoff_type:upsert";
}

/// Resource policy for TimeoffType — maps CRUD actions to permission strings.
pub struct TimeoffTypePolicy;

#[async_trait]
impl ResourcePolicy<TimeoffType> for TimeoffTypePolicy {
    async fn can(
        &self,
        action: ResourceAction,
        _entity: &TimeoffType,
        ctx: &backbone_auth::middleware::AuthContext,
    ) -> bool {
        let required = match action {
            ResourceAction::Read | ResourceAction::List => permissions::READ,
            ResourceAction::Create => permissions::CREATE,
            ResourceAction::Update | ResourceAction::Patch => permissions::UPDATE,
            ResourceAction::Delete | ResourceAction::HardDelete => permissions::DELETE,
            ResourceAction::Restore => permissions::RESTORE,
            ResourceAction::Custom(_) => return false,
        };
        ctx.permissions.iter().any(|p| p == required)
    }
}

/// Permission guard for TimeoffType handlers.
///
/// Wraps `TimeoffTypeService` and checks `TimeoffTypePolicy` before delegating.
pub type TimeoffTypeGuard = PermissionGuard<TimeoffType>;

/// Service-integrated permission guard for TimeoffType (for use in generated handlers).
pub type TimeoffTypeServiceGuard = ServicePermissionGuard<TimeoffType, TimeoffTypeService, TimeoffTypePolicy>;

// <<< CUSTOM
// END CUSTOM
