//! Auth configuration for TimeoffRequest handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Implements `ResourcePolicy<TimeoffRequest>` with entity-specific permission
//! string constants. Guard middleware logic lives in backbone-auth.

use backbone_auth::{ResourcePolicy, ResourceAction, PermissionGuard, ServicePermissionGuard};
use async_trait::async_trait;

use crate::application::service::TimeoffRequestService;
use crate::domain::entity::TimeoffRequest;

/// Permission string constants for TimeoffRequest operations.
pub mod permissions {
    pub const LIST:        &str = "timeoff_request:list";
    pub const READ:        &str = "timeoff_request:read";
    pub const CREATE:      &str = "timeoff_request:create";
    pub const UPDATE:      &str = "timeoff_request:update";
    pub const DELETE:      &str = "timeoff_request:delete";
    pub const RESTORE:     &str = "timeoff_request:restore";
    pub const TRASH:       &str = "timeoff_request:trash";
    pub const EMPTY_TRASH: &str = "timeoff_request:empty_trash";
    pub const BULK_CREATE: &str = "timeoff_request:bulk_create";
    pub const UPSERT:      &str = "timeoff_request:upsert";
}

/// Resource policy for TimeoffRequest — maps CRUD actions to permission strings.
pub struct TimeoffRequestPolicy;

#[async_trait]
impl ResourcePolicy<TimeoffRequest> for TimeoffRequestPolicy {
    async fn can(
        &self,
        action: ResourceAction,
        _entity: &TimeoffRequest,
        ctx: &backbone_auth::middleware::AuthContext,
    ) -> bool {
        let required = match action {
            ResourceAction::Read | ResourceAction::List => permissions::READ,
            ResourceAction::Create => permissions::CREATE,
            ResourceAction::Update | ResourceAction::Patch => permissions::UPDATE,
            ResourceAction::Delete | ResourceAction::HardDelete => permissions::DELETE,
            ResourceAction::Restore => permissions::RESTORE,
            ResourceAction::Custom(_) => return false,
        };
        ctx.permissions.iter().any(|p| p == required)
    }
}

/// Permission guard for TimeoffRequest handlers.
///
/// Wraps `TimeoffRequestService` and checks `TimeoffRequestPolicy` before delegating.
pub type TimeoffRequestGuard = PermissionGuard<TimeoffRequest>;

/// Service-integrated permission guard for TimeoffRequest (for use in generated handlers).
pub type TimeoffRequestServiceGuard = ServicePermissionGuard<TimeoffRequest, TimeoffRequestService, TimeoffRequestPolicy>;

// <<< CUSTOM
// END CUSTOM
