//! Auth configuration for TimeoffBalance handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Implements `ResourcePolicy<TimeoffBalance>` with entity-specific permission
//! string constants. Guard middleware logic lives in backbone-auth.

use backbone_auth::{ResourcePolicy, ResourceAction, PermissionGuard, ServicePermissionGuard};
use async_trait::async_trait;

use crate::application::service::TimeoffBalanceService;
use crate::domain::entity::TimeoffBalance;

/// Permission string constants for TimeoffBalance operations.
pub mod permissions {
    pub const LIST:        &str = "timeoff_balance:list";
    pub const READ:        &str = "timeoff_balance:read";
    pub const CREATE:      &str = "timeoff_balance:create";
    pub const UPDATE:      &str = "timeoff_balance:update";
    pub const DELETE:      &str = "timeoff_balance:delete";
    pub const RESTORE:     &str = "timeoff_balance:restore";
    pub const TRASH:       &str = "timeoff_balance:trash";
    pub const EMPTY_TRASH: &str = "timeoff_balance:empty_trash";
    pub const BULK_CREATE: &str = "timeoff_balance:bulk_create";
    pub const UPSERT:      &str = "timeoff_balance:upsert";
}

/// Resource policy for TimeoffBalance — maps CRUD actions to permission strings.
pub struct TimeoffBalancePolicy;

#[async_trait]
impl ResourcePolicy<TimeoffBalance> for TimeoffBalancePolicy {
    async fn can(
        &self,
        action: ResourceAction,
        _entity: &TimeoffBalance,
        ctx: &backbone_auth::middleware::AuthContext,
    ) -> bool {
        let required = match action {
            ResourceAction::Read | ResourceAction::List => permissions::READ,
            ResourceAction::Create => permissions::CREATE,
            ResourceAction::Update | ResourceAction::Patch => permissions::UPDATE,
            ResourceAction::Delete | ResourceAction::HardDelete => permissions::DELETE,
            ResourceAction::Restore => permissions::RESTORE,
            ResourceAction::Custom(_) => return false,
        };
        ctx.permissions.iter().any(|p| p == required)
    }
}

/// Permission guard for TimeoffBalance handlers.
///
/// Wraps `TimeoffBalanceService` and checks `TimeoffBalancePolicy` before delegating.
pub type TimeoffBalanceGuard = PermissionGuard<TimeoffBalance>;

/// Service-integrated permission guard for TimeoffBalance (for use in generated handlers).
pub type TimeoffBalanceServiceGuard = ServicePermissionGuard<TimeoffBalance, TimeoffBalanceService, TimeoffBalancePolicy>;

// <<< CUSTOM
// END CUSTOM
