//! TimeoffAccrualLevel API Integration Tests
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Tests the TimeoffAccrualLevel CRUD API endpoints.

use chrono::Utc;
use serde_json::{json, Value};
use uuid::Uuid;

use super::crud_test_base::{CrudTestConfig, GenericCrudTest, TestDataGenerator};
use crate::integration::framework::ApiTest;
use crate::integration::helpers::CommonUtils;

// ============================================================================
// TIMEOFFACCRUALLEVEL TEST DATA GENERATOR
// ============================================================================

/// Test data generator for TimeoffAccrualLevel
pub struct TimeoffAccrualLevelTestData;

impl TestDataGenerator for TimeoffAccrualLevelTestData {
    fn generate_create_payload(&self, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": Uuid::new_v4().to_string(),
            "plan_id": Uuid::new_v4().to_string(),
            "sequence": 1,
            "start_count": 0,
            "start_type": "days",
            "frequency": "daily",
            "added_value": 0,
            "is_added_based_on_worked_time": false,
            "maximum_leave": null,
            "action_with_lost_days": "nothing",
            "postponed_max_days": null,
            "metadata": json!({}),
        })
    }

    fn generate_update_payload(&self, id: &str, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": id,
            "plan_id": Uuid::new_v4().to_string(),
            "sequence": 1,
            "start_count": 0,
            "start_type": "days",
            "frequency": "daily",
            "added_value": 0,
            "is_added_based_on_worked_time": false,
            "maximum_leave": null,
            "action_with_lost_days": "nothing",
            "postponed_max_days": null,
            "metadata": json!({}),
        })
    }

    fn generate_invalid_payload(&self) -> Value {
        json!({
            // Missing required fields
        })
    }

    async fn seed_dependencies(&self, api: &ApiTest) -> Vec<(String, String)> {
        let mut deps: Vec<(String, String)> = Vec::new();
        if let Some(id) = super::crud_test_base::create_and_get_id(api, "/api/v1/timeoff_accrual_plans", &super::timeoff_accrual_plan_api_test::TimeoffAccrualPlanTestData).await {
            deps.push(("plan_id".to_string(), id));
        }
        deps
    }
}

// ============================================================================
// TIMEOFFACCRUALLEVEL API TEST
// ============================================================================

/// TimeoffAccrualLevel API test suite
pub struct TimeoffAccrualLevelApiTest {
    inner: GenericCrudTest<TimeoffAccrualLevelTestData>,
}

impl TimeoffAccrualLevelApiTest {
    pub fn new() -> Self {
        let mut config = CrudTestConfig::new("/api/v1/timeoff_accrual_levels", "TimeoffAccrualLevel");
        config.supports_soft_delete = true;
        Self {
            inner: GenericCrudTest::new(config, TimeoffAccrualLevelTestData),
        }
    }

    pub async fn run_all(&mut self) -> Vec<crate::integration::framework::TestResult> {
        self.inner.run_all().await
    }
}

impl Default for TimeoffAccrualLevelApiTest {
    fn default() -> Self {
        Self::new()
    }
}

// ============================================================================
// TESTS
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn test_timeoff_accrual_level_crud() {
        let mut test = TimeoffAccrualLevelApiTest::new();
        let results = test.run_all().await;

        for result in &results {
            println!("{:?}", result);
        }

        // Check all tests passed
        let failed: Vec<_> = results.iter().filter(|r| !r.success).collect();
        assert!(failed.is_empty(), "Some tests failed: {:?}", failed);
    }
}

// ============================================================================
// CUSTOM TESTS
// ============================================================================

// <<< CUSTOM TESTS START >>>
// Add TimeoffAccrualLevel specific tests here
// <<< CUSTOM TESTS END >>>
