//! TimeoffBalance API Integration Tests
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Tests the TimeoffBalance CRUD API endpoints.

use chrono::Utc;
use serde_json::{json, Value};
use uuid::Uuid;

use super::crud_test_base::{CrudTestConfig, GenericCrudTest, TestDataGenerator};
use crate::integration::framework::ApiTest;
use crate::integration::helpers::CommonUtils;

// ============================================================================
// TIMEOFFBALANCE TEST DATA GENERATOR
// ============================================================================

/// Test data generator for TimeoffBalance
pub struct TimeoffBalanceTestData;

impl TestDataGenerator for TimeoffBalanceTestData {
    fn generate_create_payload(&self, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": Uuid::new_v4().to_string(),
            "timeoff_type_id": Uuid::new_v4().to_string(),
            "employee_id": Uuid::new_v4().to_string(),
            "period": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "allocated": 0,
            "used": 0,
            "accrual_plan_id": null,
            "date_from": null,
            "date_to": null,
            "last_accrual_at": now,
            "carried_over": 0,
            "expired_at": now,
            "metadata": json!({}),
        })
    }

    fn generate_update_payload(&self, id: &str, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": id,
            "timeoff_type_id": Uuid::new_v4().to_string(),
            "employee_id": Uuid::new_v4().to_string(),
            "period": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "allocated": 0,
            "used": 0,
            "accrual_plan_id": null,
            "date_from": null,
            "date_to": null,
            "last_accrual_at": now,
            "carried_over": 0,
            "expired_at": now,
            "metadata": json!({}),
        })
    }

    fn generate_invalid_payload(&self) -> Value {
        json!({
            // Missing required fields
        })
    }

    async fn seed_dependencies(&self, api: &ApiTest) -> Vec<(String, String)> {
        let mut deps: Vec<(String, String)> = Vec::new();
        if let Some(id) = super::crud_test_base::create_and_get_id(api, "/api/v1/timeoff_types", &super::timeoff_type_api_test::TimeoffTypeTestData).await {
            deps.push(("timeoff_type_id".to_string(), id));
        }
        deps
    }
}

// ============================================================================
// TIMEOFFBALANCE API TEST
// ============================================================================

/// TimeoffBalance API test suite
pub struct TimeoffBalanceApiTest {
    inner: GenericCrudTest<TimeoffBalanceTestData>,
}

impl TimeoffBalanceApiTest {
    pub fn new() -> Self {
        let mut config = CrudTestConfig::new("/api/v1/timeoff_balances", "TimeoffBalance");
        config.supports_soft_delete = true;
        Self {
            inner: GenericCrudTest::new(config, TimeoffBalanceTestData),
        }
    }

    pub async fn run_all(&mut self) -> Vec<crate::integration::framework::TestResult> {
        self.inner.run_all().await
    }
}

impl Default for TimeoffBalanceApiTest {
    fn default() -> Self {
        Self::new()
    }
}

// ============================================================================
// TESTS
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn test_timeoff_balance_crud() {
        let mut test = TimeoffBalanceApiTest::new();
        let results = test.run_all().await;

        for result in &results {
            println!("{:?}", result);
        }

        // Check all tests passed
        let failed: Vec<_> = results.iter().filter(|r| !r.success).collect();
        assert!(failed.is_empty(), "Some tests failed: {:?}", failed);
    }
}

// ============================================================================
// CUSTOM TESTS
// ============================================================================

// <<< CUSTOM TESTS START >>>
// Add TimeoffBalance specific tests here
// <<< CUSTOM TESTS END >>>
