//! TimeoffType API Integration Tests
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Tests the TimeoffType CRUD API endpoints.

use chrono::Utc;
use serde_json::{json, Value};
use uuid::Uuid;

use super::crud_test_base::{CrudTestConfig, GenericCrudTest, TestDataGenerator};
use crate::integration::framework::ApiTest;
use crate::integration::helpers::CommonUtils;

// ============================================================================
// TIMEOFFTYPE TEST DATA GENERATOR
// ============================================================================

/// Test data generator for TimeoffType
pub struct TimeoffTypeTestData;

impl TestDataGenerator for TimeoffTypeTestData {
    fn generate_create_payload(&self, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": Uuid::new_v4().to_string(),
            "name": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "code": null,
            "is_paid": false,
            "allow_carry_forward": false,
            "metadata": json!({}),
        })
    }

    fn generate_update_payload(&self, id: &str, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": id,
            "name": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "code": null,
            "is_paid": false,
            "allow_carry_forward": false,
            "metadata": json!({}),
        })
    }

    fn generate_invalid_payload(&self) -> Value {
        json!({
            // Missing required fields
        })
    }
}

// ============================================================================
// TIMEOFFTYPE API TEST
// ============================================================================

/// TimeoffType API test suite
pub struct TimeoffTypeApiTest {
    inner: GenericCrudTest<TimeoffTypeTestData>,
}

impl TimeoffTypeApiTest {
    pub fn new() -> Self {
        let mut config = CrudTestConfig::new("/api/v1/timeoff_types", "TimeoffType");
        config.supports_soft_delete = true;
        Self {
            inner: GenericCrudTest::new(config, TimeoffTypeTestData),
        }
    }

    pub async fn run_all(&mut self) -> Vec<crate::integration::framework::TestResult> {
        self.inner.run_all().await
    }
}

impl Default for TimeoffTypeApiTest {
    fn default() -> Self {
        Self::new()
    }
}

// ============================================================================
// TESTS
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn test_timeoff_type_crud() {
        let mut test = TimeoffTypeApiTest::new();
        let results = test.run_all().await;

        for result in &results {
            println!("{:?}", result);
        }

        // Check all tests passed
        let failed: Vec<_> = results.iter().filter(|r| !r.success).collect();
        assert!(failed.is_empty(), "Some tests failed: {:?}", failed);
    }
}

// ============================================================================
// CUSTOM TESTS
// ============================================================================

// <<< CUSTOM TESTS START >>>
// Add TimeoffType specific tests here
// <<< CUSTOM TESTS END >>>
