//! TimeoffRequest API Integration Tests
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Tests the TimeoffRequest CRUD API endpoints.

use chrono::Utc;
use serde_json::{json, Value};
use uuid::Uuid;

use super::crud_test_base::{CrudTestConfig, GenericCrudTest, TestDataGenerator};
use crate::integration::framework::ApiTest;
use crate::integration::helpers::CommonUtils;

// ============================================================================
// TIMEOFFREQUEST TEST DATA GENERATOR
// ============================================================================

/// Test data generator for TimeoffRequest
pub struct TimeoffRequestTestData;

impl TestDataGenerator for TimeoffRequestTestData {
    fn generate_create_payload(&self, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": Uuid::new_v4().to_string(),
            "timeoff_type_id": Uuid::new_v4().to_string(),
            "employee_id": Uuid::new_v4().to_string(),
            "date_start": Utc::now().format("%Y-%m-%d").to_string(),
            "date_end": Utc::now().format("%Y-%m-%d").to_string(),
            "note": null,
            "approval_employee_id": null,
            "approval_request_id": null,
            "note_reject": null,
            "status": "pending",
            "metadata": json!({}),
        })
    }

    fn generate_update_payload(&self, id: &str, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": id,
            "timeoff_type_id": Uuid::new_v4().to_string(),
            "employee_id": Uuid::new_v4().to_string(),
            "date_start": Utc::now().format("%Y-%m-%d").to_string(),
            "date_end": Utc::now().format("%Y-%m-%d").to_string(),
            "note": null,
            "approval_employee_id": null,
            "approval_request_id": null,
            "note_reject": null,
            "status": "pending",
            "metadata": json!({}),
        })
    }

    fn generate_invalid_payload(&self) -> Value {
        json!({
            // Missing required fields
        })
    }

    async fn seed_dependencies(&self, api: &ApiTest) -> Vec<(String, String)> {
        let mut deps: Vec<(String, String)> = Vec::new();
        if let Some(id) = super::crud_test_base::create_and_get_id(api, "/api/v1/timeoff_types", &super::timeoff_type_api_test::TimeoffTypeTestData).await {
            deps.push(("timeoff_type_id".to_string(), id));
        }
        deps
    }
}

// ============================================================================
// TIMEOFFREQUEST API TEST
// ============================================================================

/// TimeoffRequest API test suite
pub struct TimeoffRequestApiTest {
    inner: GenericCrudTest<TimeoffRequestTestData>,
}

impl TimeoffRequestApiTest {
    pub fn new() -> Self {
        let mut config = CrudTestConfig::new("/api/v1/timeoff_requests", "TimeoffRequest");
        config.supports_soft_delete = true;
        Self {
            inner: GenericCrudTest::new(config, TimeoffRequestTestData),
        }
    }

    pub async fn run_all(&mut self) -> Vec<crate::integration::framework::TestResult> {
        self.inner.run_all().await
    }
}

impl Default for TimeoffRequestApiTest {
    fn default() -> Self {
        Self::new()
    }
}

// ============================================================================
// TESTS
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn test_timeoff_request_crud() {
        let mut test = TimeoffRequestApiTest::new();
        let results = test.run_all().await;

        for result in &results {
            println!("{:?}", result);
        }

        // Check all tests passed
        let failed: Vec<_> = results.iter().filter(|r| !r.success).collect();
        assert!(failed.is_empty(), "Some tests failed: {:?}", failed);
    }
}

// ============================================================================
// CUSTOM TESTS
// ============================================================================

// <<< CUSTOM TESTS START >>>
// Add TimeoffRequest specific tests here
// <<< CUSTOM TESTS END >>>
