//! HTTP route configuration
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This module provides consolidated Axum route configuration using backbone-core's
//! BackboneCrudHandler for all 12 standard Backbone CRUD endpoints per entity.

use axum::Router;
use std::sync::Arc;

use super::{
    timeoff_accrual_plan_handler::create_timeoff_accrual_plan_routes,
    timeoff_accrual_level_handler::create_timeoff_accrual_level_routes,
    timeoff_balance_handler::create_timeoff_balance_routes,
    timeoff_request_handler::create_timeoff_request_routes,
    timeoff_type_handler::create_timeoff_type_routes,
};

use crate::application::service::{
    TimeoffAccrualPlanService,
    TimeoffAccrualLevelService,
    TimeoffBalanceService,
    TimeoffRequestService,
    TimeoffTypeService,
};

/// Services collection for all CRUD endpoints
pub struct HttpServices {
    pub timeoff_accrual_plan: Arc<TimeoffAccrualPlanService>,
    pub timeoff_accrual_level: Arc<TimeoffAccrualLevelService>,
    pub timeoff_balance: Arc<TimeoffBalanceService>,
    pub timeoff_request: Arc<TimeoffRequestService>,
    pub timeoff_type: Arc<TimeoffTypeService>,
}

/// Configure all HTTP routes for this module using Axum and BackboneCrudHandler.
///
/// Each entity gets 12 standard Backbone CRUD endpoints:
/// 1. GET /api/v1/{collection} - List with pagination
/// 2. POST /api/v1/{collection} - Create
/// 3. GET /api/v1/{collection}/:id - Get by ID
/// 4. PUT /api/v1/{collection}/:id - Full update
/// 5. PATCH /api/v1/{collection}/:id - Partial update
/// 6. DELETE /api/v1/{collection}/:id - Soft delete
/// 7. POST /api/v1/{collection}/bulk - Bulk create
/// 8. POST /api/v1/{collection}/upsert - Upsert
/// 9. GET /api/v1/{collection}/trash - List deleted
/// 10. POST /api/v1/{collection}/:id/restore - Restore
/// 11. DELETE /api/v1/{collection}/empty - Empty trash
/// 12. GET /api/v1/{collection}/:id/deleted - Get deleted by ID
pub fn configure_routes(services: HttpServices) -> Router {
    Router::new()
        // TimeoffAccrualPlan routes (12 Backbone endpoints)
        .merge(create_timeoff_accrual_plan_routes(services.timeoff_accrual_plan))
        // TimeoffAccrualLevel routes (12 Backbone endpoints)
        .merge(create_timeoff_accrual_level_routes(services.timeoff_accrual_level))
        // TimeoffBalance routes (12 Backbone endpoints)
        .merge(create_timeoff_balance_routes(services.timeoff_balance))
        // TimeoffRequest routes (12 Backbone endpoints)
        .merge(create_timeoff_request_routes(services.timeoff_request))
        // TimeoffType routes (12 Backbone endpoints)
        .merge(create_timeoff_type_routes(services.timeoff_type))
}

/// Create an individual entity's routes (for modular configuration)
pub mod individual {
    use super::*;

    pub fn timeoff_accrual_plan_routes(service: Arc<TimeoffAccrualPlanService>) -> Router {
        create_timeoff_accrual_plan_routes(service)
    }

    pub fn timeoff_accrual_level_routes(service: Arc<TimeoffAccrualLevelService>) -> Router {
        create_timeoff_accrual_level_routes(service)
    }

    pub fn timeoff_balance_routes(service: Arc<TimeoffBalanceService>) -> Router {
        create_timeoff_balance_routes(service)
    }

    pub fn timeoff_request_routes(service: Arc<TimeoffRequestService>) -> Router {
        create_timeoff_request_routes(service)
    }

    pub fn timeoff_type_routes(service: Arc<TimeoffTypeService>) -> Router {
        create_timeoff_type_routes(service)
    }

}
