//! Public events for Timeoff module
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! These events are published by this module for other modules to subscribe to.
//! Events are the primary mechanism for cross-module communication.

use serde::{Deserialize, Serialize};
use chrono::{DateTime, Utc};

use super::types::*;

// ============================================================================
// TIMEOFFBALANCE EVENTS
// ============================================================================

/// Event published when a TimeoffBalance is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TimeoffBalanceCreatedEvent {
    pub id: TimeoffBalanceId,
    pub data: TimeoffBalanceDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a TimeoffBalance is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TimeoffBalanceUpdatedEvent {
    pub id: TimeoffBalanceId,
    pub data: TimeoffBalanceDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a TimeoffBalance is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TimeoffBalanceDeletedEvent {
    pub id: TimeoffBalanceId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// TIMEOFFREQUEST EVENTS
// ============================================================================

/// Event published when a TimeoffRequest is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TimeoffRequestCreatedEvent {
    pub id: TimeoffRequestId,
    pub data: TimeoffRequestDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a TimeoffRequest is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TimeoffRequestUpdatedEvent {
    pub id: TimeoffRequestId,
    pub data: TimeoffRequestDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a TimeoffRequest is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TimeoffRequestDeletedEvent {
    pub id: TimeoffRequestId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// TIMEOFFTYPE EVENTS
// ============================================================================

/// Event published when a TimeoffType is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TimeoffTypeCreatedEvent {
    pub id: TimeoffTypeId,
    pub data: TimeoffTypeDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a TimeoffType is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TimeoffTypeUpdatedEvent {
    pub id: TimeoffTypeId,
    pub data: TimeoffTypeDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a TimeoffType is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TimeoffTypeDeletedEvent {
    pub id: TimeoffTypeId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// MODULE EVENT ENUM
// ============================================================================

/// All events published by Timeoff module
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum TimeoffEvent {
    TimeoffBalanceCreated(TimeoffBalanceCreatedEvent),
    TimeoffBalanceUpdated(TimeoffBalanceUpdatedEvent),
    TimeoffBalanceDeleted(TimeoffBalanceDeletedEvent),
    TimeoffRequestCreated(TimeoffRequestCreatedEvent),
    TimeoffRequestUpdated(TimeoffRequestUpdatedEvent),
    TimeoffRequestDeleted(TimeoffRequestDeletedEvent),
    TimeoffTypeCreated(TimeoffTypeCreatedEvent),
    TimeoffTypeUpdated(TimeoffTypeUpdatedEvent),
    TimeoffTypeDeleted(TimeoffTypeDeletedEvent),
}

/// Metadata for module events
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TimeoffEventMetadata {
    pub module: &'static str,
    pub version: &'static str,
}

impl Default for TimeoffEventMetadata {
    fn default() -> Self {
        Self {
            module: "timeoff",
            version: "1.0",
        }
    }
}

// ============================================================================
// CUSTOM EVENTS
// ============================================================================

// <<< CUSTOM EVENTS START >>>
// Add custom public events here
// <<< CUSTOM EVENTS END >>>
