//! Timeoff Module Exports
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This module defines the public API that Timeoff exposes to other modules.
//! Other modules should ONLY depend on types defined here, not internal types.
//!
//! ## Usage from other modules
//!
//! ```text
//! use timeoff::exports::{TimeoffAccrualPlanDto};
//! ```

mod types;
mod services;
mod events;

// Re-export all public types
pub use types::*;
pub use services::*;
pub use events::*;

// ============================================================================
// EXPORT SUMMARY
// ============================================================================

/// Summary of what this module exports
///
/// ## Public Types
/// - `TimeoffAccrualPlanDto` - Data transfer object for TimeoffAccrualPlan
/// - `TimeoffAccrualPlanSummary` - Summary view of TimeoffAccrualPlan
/// - `TimeoffAccrualPlanId` - Type-safe ID wrapper
/// - `TimeoffAccrualLevelDto` - Data transfer object for TimeoffAccrualLevel
/// - `TimeoffAccrualLevelSummary` - Summary view of TimeoffAccrualLevel
/// - `TimeoffAccrualLevelId` - Type-safe ID wrapper
/// - `TimeoffBalanceDto` - Data transfer object for TimeoffBalance
/// - `TimeoffBalanceSummary` - Summary view of TimeoffBalance
/// - `TimeoffBalanceId` - Type-safe ID wrapper
/// - `TimeoffRequestDto` - Data transfer object for TimeoffRequest
/// - `TimeoffRequestSummary` - Summary view of TimeoffRequest
/// - `TimeoffRequestId` - Type-safe ID wrapper
/// - `TimeoffTypeDto` - Data transfer object for TimeoffType
/// - `TimeoffTypeSummary` - Summary view of TimeoffType
/// - `TimeoffTypeId` - Type-safe ID wrapper
///
/// ## Public Events
/// - `TimeoffAccrualPlanCreatedEvent` - Published when TimeoffAccrualPlan is created
/// - `TimeoffAccrualPlanUpdatedEvent` - Published when TimeoffAccrualPlan is updated
/// - `TimeoffAccrualPlanDeletedEvent` - Published when TimeoffAccrualPlan is deleted
/// - `TimeoffAccrualLevelCreatedEvent` - Published when TimeoffAccrualLevel is created
/// - `TimeoffAccrualLevelUpdatedEvent` - Published when TimeoffAccrualLevel is updated
/// - `TimeoffAccrualLevelDeletedEvent` - Published when TimeoffAccrualLevel is deleted
/// - `TimeoffBalanceCreatedEvent` - Published when TimeoffBalance is created
/// - `TimeoffBalanceUpdatedEvent` - Published when TimeoffBalance is updated
/// - `TimeoffBalanceDeletedEvent` - Published when TimeoffBalance is deleted
/// - `TimeoffRequestCreatedEvent` - Published when TimeoffRequest is created
/// - `TimeoffRequestUpdatedEvent` - Published when TimeoffRequest is updated
/// - `TimeoffRequestDeletedEvent` - Published when TimeoffRequest is deleted
/// - `TimeoffTypeCreatedEvent` - Published when TimeoffType is created
/// - `TimeoffTypeUpdatedEvent` - Published when TimeoffType is updated
/// - `TimeoffTypeDeletedEvent` - Published when TimeoffType is deleted
pub struct ExportSummary;
