//! Public services for Timeoff module
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! These services provide the public API for other modules.
//! They only expose read operations - writes go through events.

use anyhow::Result;
use async_trait::async_trait;
use chrono::NaiveDate;
use uuid::Uuid;

use super::types::*;

// ============================================================================
// QUERY SERVICE TRAIT
// ============================================================================

/// Public query service for Timeoff module
///
/// This trait defines read-only operations that other modules can use.
/// Implementations should NOT expose internal domain logic.
#[async_trait]
pub trait TimeoffQueryService: Send + Sync {
    /// Get TimeoffBalance by ID
    async fn get_timeoff_balance(&self, id: TimeoffBalanceId) -> Result<Option<TimeoffBalanceDto>>;

    /// Get TimeoffBalance summary by ID
    async fn get_timeoff_balance_summary(&self, id: TimeoffBalanceId) -> Result<Option<TimeoffBalanceSummary>>;

    /// Check if TimeoffBalance exists
    async fn timeoff_balance_exists(&self, id: TimeoffBalanceId) -> Result<bool>;

    /// Get TimeoffRequest by ID
    async fn get_timeoff_request(&self, id: TimeoffRequestId) -> Result<Option<TimeoffRequestDto>>;

    /// Get TimeoffRequest summary by ID
    async fn get_timeoff_request_summary(&self, id: TimeoffRequestId) -> Result<Option<TimeoffRequestSummary>>;

    /// Check if TimeoffRequest exists
    async fn timeoff_request_exists(&self, id: TimeoffRequestId) -> Result<bool>;

    /// Get TimeoffType by ID
    async fn get_timeoff_type(&self, id: TimeoffTypeId) -> Result<Option<TimeoffTypeDto>>;

    /// Get TimeoffType summary by ID
    async fn get_timeoff_type_summary(&self, id: TimeoffTypeId) -> Result<Option<TimeoffTypeSummary>>;

    /// Check if TimeoffType exists
    async fn timeoff_type_exists(&self, id: TimeoffTypeId) -> Result<bool>;

    /// The dates in `[from, to]` (inclusive) covered by an **approved** `TimeoffRequest` whose
    /// `TimeoffType.is_paid = true` — i.e. paid leave days, what payroll subtracts from working days.
    /// Each request's `[date_start, date_end]` is clamped to `[from, to]` and expanded into individual
    /// days. Tenancy (ADR-0029): the module is tenant-agnostic — when the composing service binds an
    /// ambient org scope, its decorator-installed row-level fence owns isolation.
    async fn paid_leave_days(
        &self,
        employee_id: Uuid,
        from: NaiveDate,
        to: NaiveDate,
    ) -> Result<Vec<NaiveDate>>;

}

// ============================================================================
// CUSTOM SERVICES
// ============================================================================

// <<< CUSTOM SERVICES START >>>
// Add custom public services here
// <<< CUSTOM SERVICES END >>>
