//! Public types for Timeoff module
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! These DTOs are the ONLY types other modules should use.
//! They are decoupled from internal domain entities.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc, NaiveDate};
use rust_decimal::Decimal;
use crate::domain::entity::*;

// ============================================================================
// TIMEOFFACCRUALPLAN TYPES
// ============================================================================

/// Type-safe ID for TimeoffAccrualPlan
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct TimeoffAccrualPlanId(pub Uuid);

impl TimeoffAccrualPlanId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for TimeoffAccrualPlanId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<TimeoffAccrualPlanId> for Uuid {
    fn from(id: TimeoffAccrualPlanId) -> Self {
        id.0
    }
}

/// Data transfer object for TimeoffAccrualPlan
///
/// This is the public representation of TimeoffAccrualPlan for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TimeoffAccrualPlanDto {
    pub id: TimeoffAccrualPlanId,
    pub company_id: Uuid,
    pub timeoff_type_id: Uuid,
    pub name: String,
    pub metadata: serde_json::Value,
}

/// Summary view of TimeoffAccrualPlan for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TimeoffAccrualPlanSummary {
    pub id: TimeoffAccrualPlanId,
    pub name: String,
}

/// Reference to TimeoffAccrualPlan for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TimeoffAccrualPlanRef {
    pub id: TimeoffAccrualPlanId,
}

// ============================================================================
// TIMEOFFACCRUALLEVEL TYPES
// ============================================================================

/// Type-safe ID for TimeoffAccrualLevel
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct TimeoffAccrualLevelId(pub Uuid);

impl TimeoffAccrualLevelId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for TimeoffAccrualLevelId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<TimeoffAccrualLevelId> for Uuid {
    fn from(id: TimeoffAccrualLevelId) -> Self {
        id.0
    }
}

/// Data transfer object for TimeoffAccrualLevel
///
/// This is the public representation of TimeoffAccrualLevel for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TimeoffAccrualLevelDto {
    pub id: TimeoffAccrualLevelId,
    pub company_id: Uuid,
    pub plan_id: Uuid,
    pub sequence: i32,
    pub start_count: Decimal,
    pub start_type: AccrualStartType,
    pub frequency: AccrualFrequency,
    pub added_value: Decimal,
    pub is_added_based_on_worked_time: bool,
    pub maximum_leave: Option<Decimal>,
    pub action_with_lost_days: AccrualLostDaysAction,
    pub postponed_max_days: Option<Decimal>,
    pub metadata: serde_json::Value,
}

/// Summary view of TimeoffAccrualLevel for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TimeoffAccrualLevelSummary {
    pub id: TimeoffAccrualLevelId,
}

/// Reference to TimeoffAccrualLevel for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TimeoffAccrualLevelRef {
    pub id: TimeoffAccrualLevelId,
}

// ============================================================================
// TIMEOFFBALANCE TYPES
// ============================================================================

/// Type-safe ID for TimeoffBalance
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct TimeoffBalanceId(pub Uuid);

impl TimeoffBalanceId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for TimeoffBalanceId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<TimeoffBalanceId> for Uuid {
    fn from(id: TimeoffBalanceId) -> Self {
        id.0
    }
}

/// Data transfer object for TimeoffBalance
///
/// This is the public representation of TimeoffBalance for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TimeoffBalanceDto {
    pub id: TimeoffBalanceId,
    pub company_id: Uuid,
    pub timeoff_type_id: Uuid,
    pub employee_id: Uuid,
    pub period: String,
    pub allocated: Decimal,
    pub used: Decimal,
    pub accrual_plan_id: Option<Uuid>,
    pub date_from: Option<NaiveDate>,
    pub date_to: Option<NaiveDate>,
    pub last_accrual_at: Option<DateTime<Utc>>,
    pub carried_over: Decimal,
    pub expired_at: Option<DateTime<Utc>>,
    pub metadata: serde_json::Value,
}

/// Summary view of TimeoffBalance for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TimeoffBalanceSummary {
    pub id: TimeoffBalanceId,
}

/// Reference to TimeoffBalance for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TimeoffBalanceRef {
    pub id: TimeoffBalanceId,
}

// ============================================================================
// TIMEOFFREQUEST TYPES
// ============================================================================

/// Type-safe ID for TimeoffRequest
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct TimeoffRequestId(pub Uuid);

impl TimeoffRequestId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for TimeoffRequestId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<TimeoffRequestId> for Uuid {
    fn from(id: TimeoffRequestId) -> Self {
        id.0
    }
}

/// Data transfer object for TimeoffRequest
///
/// This is the public representation of TimeoffRequest for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TimeoffRequestDto {
    pub id: TimeoffRequestId,
    pub company_id: Uuid,
    pub timeoff_type_id: Uuid,
    pub employee_id: Uuid,
    pub date_start: NaiveDate,
    pub date_end: NaiveDate,
    pub note: Option<String>,
    pub approval_employee_id: Option<Uuid>,
    pub approval_request_id: Option<Uuid>,
    pub note_reject: Option<String>,
    pub status: TimeoffRequestStatus,
    pub metadata: serde_json::Value,
}

/// Summary view of TimeoffRequest for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TimeoffRequestSummary {
    pub id: TimeoffRequestId,
    pub status: TimeoffRequestStatus,
}

/// Reference to TimeoffRequest for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TimeoffRequestRef {
    pub id: TimeoffRequestId,
}

// ============================================================================
// TIMEOFFTYPE TYPES
// ============================================================================

/// Type-safe ID for TimeoffType
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct TimeoffTypeId(pub Uuid);

impl TimeoffTypeId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for TimeoffTypeId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<TimeoffTypeId> for Uuid {
    fn from(id: TimeoffTypeId) -> Self {
        id.0
    }
}

/// Data transfer object for TimeoffType
///
/// This is the public representation of TimeoffType for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TimeoffTypeDto {
    pub id: TimeoffTypeId,
    pub company_id: Uuid,
    pub name: String,
    pub code: Option<String>,
    pub is_paid: bool,
    pub allow_carry_forward: bool,
    pub metadata: serde_json::Value,
}

/// Summary view of TimeoffType for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TimeoffTypeSummary {
    pub id: TimeoffTypeId,
    pub name: String,
}

/// Reference to TimeoffType for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TimeoffTypeRef {
    pub id: TimeoffTypeId,
}

// ============================================================================
// CUSTOM TYPES
// ============================================================================

// <<< CUSTOM TYPES START >>>
// Add custom public types here
// <<< CUSTOM TYPES END >>>
