//! Timeoff Module
//!
//! Generated by metaphor-schema. Enhanced with runtime implementations.
//!
//! This module provides:
//! - Domain entities and repositories
//! - Application services
//! - HTTP and gRPC handlers
//! - Route configuration
//! - State machine enforcement
//! - Validation rules runtime
//! - RBAC middleware
//! - Trigger execution system
//! - Computed fields
//! - Workflow orchestrator

#![recursion_limit = "1024"]
#![allow(unused_imports)]

// Generated modules
pub mod domain;
pub mod infrastructure;
pub mod application;
pub mod presentation;
pub mod seeders;
pub mod exports;

// Re-exports for convenience - Domain entities
pub use domain::entity::*;

// Re-exports - Infrastructure
pub use infrastructure::persistence::*;

// Re-exports - Application services
pub use application::service::TimeoffAccrualPlanService;
pub use application::service::TimeoffAccrualLevelService;
pub use application::service::TimeoffBalanceService;
pub use application::service::TimeoffRequestService;
pub use application::service::TimeoffTypeService;

// Re-exports - Workflows
pub use application::workflows::*;

use std::sync::Arc;
use axum::Router;
use sqlx::PgPool;

/// Timeoff module configuration
///
/// Use the builder pattern to configure and register this module:
///
/// ```text
/// let timeoff = TimeoffModule::builder()
///     .with_database(pool.clone())
///     .build()?;
///
/// // Unguarded full CRUD (trusted/admin); compose a guarded router for production.
/// let router = timeoff.all_crud_routes();
/// ```
pub struct TimeoffModule {
    pub(crate) timeoff_accrual_plan_service: Arc<TimeoffAccrualPlanService>,
    pub(crate) timeoff_accrual_level_service: Arc<TimeoffAccrualLevelService>,
    pub(crate) timeoff_balance_service: Arc<TimeoffBalanceService>,
    pub(crate) timeoff_request_service: Arc<TimeoffRequestService>,
    pub(crate) timeoff_type_service: Arc<TimeoffTypeService>,
    // <<< CUSTOM FIELDS
    // Held so the `TimeoffQueryService` impl can delegate `paid_leave_days` to the repo's
    // hand-written SQL, and standard lookups to the CRUD services above. `db_pool` is the same pool
    // the repo was constructed with (the repo's `paid_leave_days` takes it per the backbone-attendance
    // read-port convention — RLS scoping is applied inside via `company_scope::fetch_all_scoped`).
    pub(crate) timeoff_request_repository: Arc<TimeoffRequestRepository>,
    // The balance repo + write service are wired here so the leave-drawdown invariant is live on the
    // module, but no in-crate handler drives them yet (the approve/reject/cancel HTTP surface and a
    // public accessor land in the next phase, alongside the outbox/compound-event wiring per ADR-005).
    // `#[allow(dead_code)]` is honest about that — the service is fully functional, just not yet
    // called from inside this crate.
    #[allow(dead_code)]
    pub(crate) timeoff_balance_repository: Arc<TimeoffBalanceRepository>,
    #[allow(dead_code)]
    pub(crate) timeoff_write_service: Arc<application::service::TimeoffRequestWriteService>,
    pub(crate) db_pool: sqlx::PgPool,
    // END CUSTOM
}

impl TimeoffModule {
    /// Create a new module builder
    pub fn builder() -> TimeoffModuleBuilder {
        TimeoffModuleBuilder::new()
    }

    /// Mount ALL generated CRUD endpoints (12 per entity) with NO domain
    /// validation — the fully **unguarded** surface. A well-formed request can
    /// create invalid rows or soft-delete a referenced master out from under its
    /// dependents. Prefer a guarded composition (read + validated writes) for any
    /// real deployment; use this only in trusted/admin/seeding contexts.
    pub fn all_crud_routes(&self) -> Router {
        use presentation::http::{
            create_timeoff_accrual_plan_routes,
            create_timeoff_accrual_level_routes,
            create_timeoff_balance_routes,
            create_timeoff_request_routes,
            create_timeoff_type_routes,
        };

        Router::new()
            .merge(create_timeoff_accrual_plan_routes(self.timeoff_accrual_plan_service.clone()))
            .merge(create_timeoff_accrual_level_routes(self.timeoff_accrual_level_service.clone()))
            .merge(create_timeoff_balance_routes(self.timeoff_balance_service.clone()))
            .merge(create_timeoff_request_routes(self.timeoff_request_service.clone()))
            .merge(create_timeoff_type_routes(self.timeoff_type_service.clone()))
    }

    /// Deprecated alias for [`Self::all_crud_routes`]. `routes()` reads like
    /// "the routes" but mounts UNVALIDATED generic CRUD on every entity — a naive
    /// mount exposes unguarded writes. Compose a guarded router (read + validated
    /// writes) for production, or call `all_crud_routes()` to opt into the full
    /// unguarded surface explicitly.
    #[deprecated(note = "mounts unvalidated generic CRUD; prefer readonly_routes() + validated writes, or all_crud_routes() for the full/unguarded surface")]
    pub fn routes(&self) -> Router {
        self.all_crud_routes()
    }

    /// Read-only routes for every entity (GET endpoints only) — the safe base.
    ///
    /// Generic mutation can't reach here, so this surface cannot bypass a
    /// validated write service's invariants. Use this as the production base and
    /// merge validated write routes (or a write service's HTTP layer) onto it.
    pub fn readonly_routes(&self) -> Router {
        use presentation::http::{
            create_timeoff_accrual_plan_read_routes,
            create_timeoff_accrual_level_read_routes,
            create_timeoff_balance_read_routes,
            create_timeoff_request_read_routes,
            create_timeoff_type_read_routes,
        };

        Router::new()
            .merge(create_timeoff_accrual_plan_read_routes(self.timeoff_accrual_plan_service.clone()))
            .merge(create_timeoff_accrual_level_read_routes(self.timeoff_accrual_level_service.clone()))
            .merge(create_timeoff_balance_read_routes(self.timeoff_balance_service.clone()))
            .merge(create_timeoff_request_read_routes(self.timeoff_request_service.clone()))
            .merge(create_timeoff_type_read_routes(self.timeoff_type_service.clone()))
    }

    // <<< CUSTOM METHODS
    /// The module-held validated write path (request verbs + the approvals seam).
    pub fn timeoff_write_service(&self) -> Arc<application::service::TimeoffRequestWriteService> {
        self.timeoff_write_service.clone()
    }

    /// Replace the write service at the composition root — the way a host arms the approvals
    /// seam: the module builds the service internally (default-unwired), so the app builds its
    /// own from the same pool with the port attached and swaps it in. Consuming `self` keeps
    /// the chain reading naturally; call before mounting routes, the module is consumed once
    /// at startup.
    ///
    /// ```text
    /// let timeoff = TimeoffModule::builder()
    ///     .with_database(pool.clone())
    ///     .build()?
    ///     .with_timeoff_write_service(Arc::new(
    ///         TimeoffRequestWriteService::new(pool.clone()).with_approvals(port),
    ///     ));
    /// ```
    pub fn with_timeoff_write_service(
        mut self,
        svc: Arc<application::service::TimeoffRequestWriteService>,
    ) -> Self {
        self.timeoff_write_service = svc;
        self
    }
    // END CUSTOM
}

/// Builder for TimeoffModule
pub struct TimeoffModuleBuilder {
    db_pool: Option<PgPool>,
}

impl TimeoffModuleBuilder {
    /// Create a new builder
    pub fn new() -> Self {
        Self {
            db_pool: None,
        }
    }

    /// Set the database connection pool
    pub fn with_database(mut self, pool: PgPool) -> Self {
        self.db_pool = Some(pool);
        self
    }

    // <<< CUSTOM - custom builder methods
    // END CUSTOM

    /// Build the module with configured dependencies
    pub fn build(self) -> anyhow::Result<TimeoffModule> {
        let db_pool = self.db_pool
            .ok_or_else(|| anyhow::anyhow!("Database pool not configured"))?;

        // TimeoffAccrualPlan service
        let timeoff_accrual_plan_repository = Arc::new(TimeoffAccrualPlanRepository::new(db_pool.clone()));
        let timeoff_accrual_plan_service = Arc::new(TimeoffAccrualPlanService::with_repository(timeoff_accrual_plan_repository.clone()));

        // TimeoffAccrualLevel service
        let timeoff_accrual_level_repository = Arc::new(TimeoffAccrualLevelRepository::new(db_pool.clone()));
        let timeoff_accrual_level_service = Arc::new(TimeoffAccrualLevelService::with_repository(timeoff_accrual_level_repository.clone()));

        // TimeoffBalance service
        let timeoff_balance_repository = Arc::new(TimeoffBalanceRepository::new(db_pool.clone()));
        let timeoff_balance_service = Arc::new(TimeoffBalanceService::with_repository(timeoff_balance_repository.clone()));

        // TimeoffRequest service
        let timeoff_request_repository = Arc::new(TimeoffRequestRepository::new(db_pool.clone()));
        let timeoff_request_service = Arc::new(TimeoffRequestService::with_repository(timeoff_request_repository.clone()));

        // TimeoffType service
        let timeoff_type_repository = Arc::new(TimeoffTypeRepository::new(db_pool.clone()));
        let timeoff_type_service = Arc::new(TimeoffTypeService::with_repository(timeoff_type_repository.clone()));

        // <<< CUSTOM
        // Retain the timeoff-request repo + pool on the module so the `TimeoffQueryService` impl can
        // delegate `paid_leave_days` (custom SQL on the repo) and supply the pool the repo method takes.
        // Construct the hand-authored leave-drawdown write service from the same pool — it owns the
        // approve/reject/cancel transitions and pairs them with the balance repo's draw/restore inside
        // one transaction (ported verbatim from backbone-hr's hr_write_service.rs).
        let timeoff_write_service = Arc::new(application::service::TimeoffRequestWriteService::new(db_pool.clone()));
        // END CUSTOM

        Ok(TimeoffModule {
            timeoff_accrual_plan_service,
            timeoff_accrual_level_service,
            timeoff_balance_service,
            timeoff_request_service,
            timeoff_type_service,
            // <<< CUSTOM
            timeoff_request_repository: timeoff_request_repository.clone(),
            timeoff_balance_repository: timeoff_balance_repository.clone(),
            timeoff_write_service,
            db_pool,
            // END CUSTOM
        })
    }
}

impl Default for TimeoffModuleBuilder {
    fn default() -> Self {
        Self::new()
    }
}