//! Application use cases
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each entity contributes 5 type aliases (create, update, get, delete, list).

pub mod base;
pub use base::{UseCaseError, UseCaseResult, UseCaseHooks};

pub mod timeoff_balance_usecases;
pub mod timeoff_request_usecases;
pub mod timeoff_type_usecases;

pub use timeoff_balance_usecases::{
    CreateTimeoffBalanceUseCase, UpdateTimeoffBalanceUseCase, GetTimeoffBalanceUseCase,
    DeleteTimeoffBalanceUseCase, ListTimeoffBalanceUseCase,
};
pub use timeoff_request_usecases::{
    CreateTimeoffRequestUseCase, UpdateTimeoffRequestUseCase, GetTimeoffRequestUseCase,
    DeleteTimeoffRequestUseCase, ListTimeoffRequestUseCase,
};
pub use timeoff_type_usecases::{
    CreateTimeoffTypeUseCase, UpdateTimeoffTypeUseCase, GetTimeoffTypeUseCase,
    DeleteTimeoffTypeUseCase, ListTimeoffTypeUseCase,
};

// <<< CUSTOM
// END CUSTOM
