//! Use case type aliases for TimeoffType aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each alias delegates to the matching generic use case in backbone-core.
//! Custom pre/post hooks go in `UseCaseHooks` implementations (// <<< CUSTOM).

use backbone_core::{
    CreateUseCase, UpdateUseCase, GetUseCase, DeleteUseCase, ListUseCase,
};

use crate::presentation::dto::{CreateTimeoffTypeDto, UpdateTimeoffTypeDto};
use crate::application::service::TimeoffTypeService;
use crate::domain::entity::TimeoffType;

// ─── Use case type aliases ───────────────────────────────────────────────────

pub type CreateTimeoffTypeUseCase = CreateUseCase<TimeoffType, CreateTimeoffTypeDto, TimeoffTypeService>;
pub type UpdateTimeoffTypeUseCase = UpdateUseCase<TimeoffType, UpdateTimeoffTypeDto, TimeoffTypeService>;
pub type GetTimeoffTypeUseCase    = GetUseCase<TimeoffType, TimeoffTypeService>;
pub type DeleteTimeoffTypeUseCase = DeleteUseCase<TimeoffType, TimeoffTypeService>;
pub type ListTimeoffTypeUseCase   = ListUseCase<TimeoffType, TimeoffTypeService>;

// <<< CUSTOM
// END CUSTOM
