//! Use case type aliases for TimeoffRequest aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each alias delegates to the matching generic use case in backbone-core.
//! Custom pre/post hooks go in `UseCaseHooks` implementations (// <<< CUSTOM).

use backbone_core::{
    CreateUseCase, UpdateUseCase, GetUseCase, DeleteUseCase, ListUseCase,
};

use crate::presentation::dto::{CreateTimeoffRequestDto, UpdateTimeoffRequestDto};
use crate::application::service::TimeoffRequestService;
use crate::domain::entity::TimeoffRequest;

// ─── Use case type aliases ───────────────────────────────────────────────────

pub type CreateTimeoffRequestUseCase = CreateUseCase<TimeoffRequest, CreateTimeoffRequestDto, TimeoffRequestService>;
pub type UpdateTimeoffRequestUseCase = UpdateUseCase<TimeoffRequest, UpdateTimeoffRequestDto, TimeoffRequestService>;
pub type GetTimeoffRequestUseCase    = GetUseCase<TimeoffRequest, TimeoffRequestService>;
pub type DeleteTimeoffRequestUseCase = DeleteUseCase<TimeoffRequest, TimeoffRequestService>;
pub type ListTimeoffRequestUseCase   = ListUseCase<TimeoffRequest, TimeoffRequestService>;

// <<< CUSTOM
// END CUSTOM
