//! Use case type aliases for TimeoffBalance aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each alias delegates to the matching generic use case in backbone-core.
//! Custom pre/post hooks go in `UseCaseHooks` implementations (// <<< CUSTOM).

use backbone_core::{
    CreateUseCase, UpdateUseCase, GetUseCase, DeleteUseCase, ListUseCase,
};

use crate::presentation::dto::{CreateTimeoffBalanceDto, UpdateTimeoffBalanceDto};
use crate::application::service::TimeoffBalanceService;
use crate::domain::entity::TimeoffBalance;

// ─── Use case type aliases ───────────────────────────────────────────────────

pub type CreateTimeoffBalanceUseCase = CreateUseCase<TimeoffBalance, CreateTimeoffBalanceDto, TimeoffBalanceService>;
pub type UpdateTimeoffBalanceUseCase = UpdateUseCase<TimeoffBalance, UpdateTimeoffBalanceDto, TimeoffBalanceService>;
pub type GetTimeoffBalanceUseCase    = GetUseCase<TimeoffBalance, TimeoffBalanceService>;
pub type DeleteTimeoffBalanceUseCase = DeleteUseCase<TimeoffBalance, TimeoffBalanceService>;
pub type ListTimeoffBalanceUseCase   = ListUseCase<TimeoffBalance, TimeoffBalanceService>;

// <<< CUSTOM
// END CUSTOM
